#include "renderer.h"
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <cmath>
#include <cstdint>
#include <SDL3/SDL.h>
#include "sokol_app.h"
#include "sokol_gfx.h"
#include "sokol_glue.h"
#if defined(SOKOL_GLCORE)
#ifndef GL_GLEXT_PROTOTYPES
#define GL_GLEXT_PROTOTYPES
#endif
#include <SDL3/SDL_opengl.h>
#endif
#include "imgui.h"
#include "sokol_imgui.h"
#include "profiler.h"
#include "maths.h"

// Generated by sokol-shdc; included via third_party_impl.cpp's translation
// unit for the impls, and here for the {prog}_shader_desc() helpers and the
// SLOT_*, UB_*, VIEW_*, SMP_*, and UB struct definitions.
#include "shaders/wireframe.glsl.h"
#include "shaders/overlay.glsl.h"
#include "shaders/darken.glsl.h"
#include "shaders/mesh.glsl.h"
#include "shaders/splat.glsl.h"
#include "shaders/cull.glsl.h"
#include "shaders/sort.glsl.h"
#include "shaders/accum.glsl.h"
#include "shaders/gps.glsl.h"

sg_pixel_format renderer_default_color_format(void) {
    if (sg_isvalid()) {
        return sg_query_desc().environment.defaults.color_format;
    }
    return SG_PIXELFORMAT_RGBA8;
}

static void renderer_destroy_shader_pipeline(sg_pipeline* pipeline) {
    if (!pipeline->id) return;
    sg_pipeline_desc desc = sg_query_pipeline_desc(*pipeline);
    sg_destroy_pipeline(*pipeline);
    if (desc.shader.id) sg_destroy_shader(desc.shader);
    *pipeline = {};
}

static void renderer_destroy_shader_pipelines(Renderer* r) {
    renderer_destroy_shader_pipeline(&r->splat_pipeline);
    renderer_destroy_shader_pipeline(&r->splat_stochastic_pipeline);
    renderer_destroy_shader_pipeline(&r->cull_pipeline);
    renderer_destroy_shader_pipeline(&r->cull_reset_pipeline);
    renderer_destroy_shader_pipeline(&r->radix_hist_pipeline);
    renderer_destroy_shader_pipeline(&r->radix_prefix_pipeline);
    renderer_destroy_shader_pipeline(&r->radix_scatter_pipeline);
    renderer_destroy_shader_pipeline(&r->gps_clear_pipeline);
    renderer_destroy_shader_pipeline(&r->gps_splat_pipeline);
    renderer_destroy_shader_pipeline(&r->gps_resolve_pipeline);
    renderer_destroy_shader_pipeline(&r->accum_pipeline);
    renderer_destroy_shader_pipeline(&r->taa_accum_pipeline);
    renderer_destroy_shader_pipeline(&r->blit_pipeline);
    renderer_destroy_shader_pipeline(&r->overlay_pipeline);
    renderer_destroy_shader_pipeline(&r->darken_pipeline);
    renderer_destroy_shader_pipeline(&r->wireframe_pipeline);
    renderer_destroy_shader_pipeline(&r->mesh_pipeline);
}

static uint32_t next_power_of_two_u32(uint32_t v) {
    if (v <= 1u) return 1u;
    v--;
    v |= v >> 1;
    v |= v >> 2;
    v |= v >> 4;
    v |= v >> 8;
    v |= v >> 16;
    return v + 1u;
}

static bool mat4_inverse(const float m[16], float inv_out[16]) {
    float inv[16];

    inv[0] = m[5]  * m[10] * m[15] -
             m[5]  * m[11] * m[14] -
             m[9]  * m[6]  * m[15] +
             m[9]  * m[7]  * m[14] +
             m[13] * m[6]  * m[11] -
             m[13] * m[7]  * m[10];

    inv[4] = -m[4]  * m[10] * m[15] +
              m[4]  * m[11] * m[14] +
              m[8]  * m[6]  * m[15] -
              m[8]  * m[7]  * m[14] -
              m[12] * m[6]  * m[11] +
              m[12] * m[7]  * m[10];

    inv[8] = m[4]  * m[9] * m[15] -
             m[4]  * m[11] * m[13] -
             m[8]  * m[5] * m[15] +
             m[8]  * m[7] * m[13] +
             m[12] * m[5] * m[11] -
             m[12] * m[7] * m[9];

    inv[12] = -m[4]  * m[9] * m[14] +
               m[4]  * m[10] * m[13] +
               m[8]  * m[5] * m[14] -
               m[8]  * m[6] * m[13] -
               m[12] * m[5] * m[10] +
               m[12] * m[6] * m[9];

    inv[1] = -m[1]  * m[10] * m[15] +
              m[1]  * m[11] * m[14] +
              m[9]  * m[2] * m[15] -
              m[9]  * m[3] * m[14] -
              m[13] * m[2] * m[11] +
              m[13] * m[3] * m[10];

    inv[5] = m[0]  * m[10] * m[15] -
             m[0]  * m[11] * m[14] -
             m[8]  * m[2] * m[15] +
             m[8]  * m[3] * m[14] +
             m[12] * m[2] * m[11] -
             m[12] * m[3] * m[10];

    inv[9] = -m[0]  * m[9] * m[15] +
              m[0]  * m[11] * m[13] +
              m[8]  * m[1] * m[15] -
              m[8]  * m[3] * m[13] -
              m[12] * m[1] * m[11] +
              m[12] * m[3] * m[9];

    inv[13] = m[0]  * m[9] * m[14] -
              m[0]  * m[10] * m[13] -
              m[8]  * m[1] * m[14] +
              m[8]  * m[2] * m[13] +
              m[12] * m[1] * m[10] -
              m[12] * m[2] * m[9];

    inv[2] = m[1]  * m[6] * m[15] -
             m[1]  * m[7] * m[14] -
             m[5]  * m[2] * m[15] +
             m[5]  * m[3] * m[14] +
             m[13] * m[2] * m[7] -
             m[13] * m[3] * m[6];

    inv[6] = -m[0]  * m[6] * m[15] +
              m[0]  * m[7] * m[14] +
              m[4]  * m[2] * m[15] -
              m[4]  * m[3] * m[14] -
              m[12] * m[2] * m[7] +
              m[12] * m[3] * m[6];

    inv[10] = m[0]  * m[5] * m[15] -
              m[0]  * m[7] * m[13] -
              m[4]  * m[1] * m[15] +
              m[4]  * m[3] * m[13] +
              m[12] * m[1] * m[7] -
              m[12] * m[3] * m[5];

    inv[14] = -m[0]  * m[5] * m[14] +
               m[0]  * m[6] * m[13] +
               m[4]  * m[1] * m[14] -
               m[4]  * m[2] * m[13] -
               m[12] * m[1] * m[6] +
               m[12] * m[2] * m[5];

    inv[3] = -m[1] * m[6] * m[11] +
              m[1] * m[7] * m[10] +
              m[5] * m[2] * m[11] -
              m[5] * m[3] * m[10] -
              m[9] * m[2] * m[7] +
              m[9] * m[3] * m[6];

    inv[7] = m[0] * m[6] * m[11] -
             m[0] * m[7] * m[10] -
             m[4] * m[2] * m[11] +
             m[4] * m[3] * m[10] +
             m[8] * m[2] * m[7] -
             m[8] * m[3] * m[6];

    inv[11] = -m[0] * m[5] * m[11] +
               m[0] * m[7] * m[9] +
               m[4] * m[1] * m[11] -
               m[4] * m[3] * m[9] -
               m[8] * m[1] * m[7] +
               m[8] * m[3] * m[5];

    inv[15] = m[0] * m[5] * m[10] -
              m[0] * m[6] * m[9] -
              m[4] * m[1] * m[10] +
              m[4] * m[2] * m[9] +
              m[8] * m[1] * m[6] -
              m[8] * m[2] * m[5];

    float det = m[0] * inv[0] + m[1] * inv[4] + m[2] * inv[8] + m[3] * inv[12];
    if (fabsf(det) <= 1.0e-8f) return false;

    det = 1.0f / det;
    for (int i = 0; i < 16; i++) inv_out[i] = inv[i] * det;
    return true;
}

#if defined(SOKOL_GLCORE)
static bool gl_has_extension(const char* name) {
    GLint extension_count = 0;
    glGetIntegerv(GL_NUM_EXTENSIONS, &extension_count);
    for (GLint i = 0; i < extension_count; ++i) {
        const char* extension = (const char*)glGetStringi(GL_EXTENSIONS, (GLuint)i);
        if (extension && strcmp(extension, name) == 0) {
            return true;
        }
    }
    return false;
}
#endif

static GpsCapabilities renderer_query_gps_capabilities(void) {
    GpsCapabilities caps = {};
    sg_features features = sg_query_features();
    sg_limits limits = sg_query_limits();

    caps.compute = features.compute;
    caps.storage_images = limits.max_storage_image_bindings_per_stage > 0;

#if defined(SOKOL_GLCORE)
    // GPS needs 64-bit packed depth/color atomics. Sokol exposes compute and
    // storage-image limits, but not shader-int64/64-bit atomic support, so GL
    // backends query the relevant extensions directly. Other backends stay
    // unsupported until their shader/codegen path is explicitly validated.
    caps.shader_int64 = gl_has_extension("GL_ARB_gpu_shader_int64");
    caps.atomic_min_64 = gl_has_extension("GL_NV_shader_atomic_int64") ||
                         gl_has_extension("GL_EXT_shader_image_int64");
#endif

    caps.supported = caps.compute && caps.storage_images &&
                     caps.shader_int64 && caps.atomic_min_64;
    return caps;
}

static float halton(uint32_t index, uint32_t base) {
    float f = 1.0f;
    float r = 0.0f;
    while (index > 0) {
        f /= (float)base;
        r += f * (float)(index % base);
        index /= base;
    }
    return r;
}

struct StochasticSampleViews {
    sg_view color_texture;
    sg_view depth_texture;
};

static bool renderer_create_shader_pipelines(Renderer* r) {
    // --- Splat pipeline -------------------------------------------------
    {
        sg_pipeline_desc pd = {};
        pd.shader = sg_make_shader(splat_shader_desc(sg_query_backend()));
        pd.primitive_type = SG_PRIMITIVETYPE_TRIANGLES;
        // Splats only test depth (so they don't poke through the mesh from
        // behind), they don't write depth or stencil.
        pd.depth.compare = SG_COMPAREFUNC_LESS;
        pd.depth.write_enabled = false;
        pd.depth.pixel_format = SG_PIXELFORMAT_DEPTH_STENCIL;
        pd.cull_mode = SG_CULLMODE_NONE;
        pd.colors[0].pixel_format = renderer_default_color_format();
        pd.colors[0].blend.enabled = true;
        pd.colors[0].blend.src_factor_rgb = SG_BLENDFACTOR_ONE;
        pd.colors[0].blend.dst_factor_rgb = SG_BLENDFACTOR_ONE_MINUS_SRC_ALPHA;
        pd.colors[0].blend.op_rgb = SG_BLENDOP_ADD;
        // Alpha factor preserves the previous behavior where the alpha
        // channel was scaled by a "blend constant" to control occlusion of
        // the wireframe pass. sokol_gfx has no equivalent of
        // SDL_SetGPUBlendConstants, so this stage now uses ONE/ONE-MINUS
        // for alpha — wireframe_occlusion is therefore no longer honored.
        pd.colors[0].blend.src_factor_alpha = SG_BLENDFACTOR_ONE;
        pd.colors[0].blend.dst_factor_alpha = SG_BLENDFACTOR_ONE_MINUS_SRC_ALPHA;
        pd.colors[0].blend.op_alpha = SG_BLENDOP_ADD;
        pd.colors[0].write_mask = SG_COLORMASK_RGBA;
        pd.label = "splat-pipeline";
        r->splat_pipeline = sg_make_pipeline(&pd);
    }

    // --- Stochastic splat pipeline --------------------------------------
    {
        sg_pipeline_desc pd = {};
        pd.shader = sg_make_shader(splat_stochastic_shader_desc(sg_query_backend()));
        pd.primitive_type = SG_PRIMITIVETYPE_TRIANGLES;
        pd.depth.compare = SG_COMPAREFUNC_LESS;
        pd.depth.write_enabled = true;
        pd.depth.pixel_format = SG_PIXELFORMAT_DEPTH_STENCIL;
        pd.cull_mode = SG_CULLMODE_NONE;
        pd.colors[0].pixel_format = renderer_default_color_format();
        pd.colors[0].blend.enabled = false;
        pd.colors[0].write_mask = SG_COLORMASK_RGBA;
        pd.label = "splat-stochastic-pipeline";
        r->splat_stochastic_pipeline = sg_make_pipeline(&pd);
    }

    // --- Gaussian cull/depth-key compute pipeline -----------------------
    {
        sg_pipeline_desc pd = {};
        pd.compute = true;
        pd.shader = sg_make_shader(cull_shader_desc(sg_query_backend()));
        pd.label = "gaussian-cull-pipeline";
        r->cull_pipeline = sg_make_pipeline(&pd);
    }
    {
        sg_pipeline_desc pd = {};
        pd.compute = true;
        pd.shader = sg_make_shader(cull_reset_shader_desc(sg_query_backend()));
        pd.label = "gaussian-cull-reset-pipeline";
        r->cull_reset_pipeline = sg_make_pipeline(&pd);
    }

    // --- Alpha-blend radix sort compute pipelines -----------------------
    {
        sg_pipeline_desc pd = {};
        pd.compute = true;
        pd.shader = sg_make_shader(radix_hist_shader_desc(sg_query_backend()));
        pd.label = "gaussian-radix-hist-pipeline";
        r->radix_hist_pipeline = sg_make_pipeline(&pd);
    }
    {
        sg_pipeline_desc pd = {};
        pd.compute = true;
        pd.shader = sg_make_shader(radix_prefix_shader_desc(sg_query_backend()));
        pd.label = "gaussian-radix-prefix-pipeline";
        r->radix_prefix_pipeline = sg_make_pipeline(&pd);
    }
    {
        sg_pipeline_desc pd = {};
        pd.compute = true;
        pd.shader = sg_make_shader(radix_scatter_shader_desc(sg_query_backend()));
        pd.label = "gaussian-radix-scatter-pipeline";
        r->radix_scatter_pipeline = sg_make_pipeline(&pd);
    }

    // --- Experimental Gaussian Point Splatting prototype pipelines -------
    {
        sg_pipeline_desc pd = {};
        pd.compute = true;
        pd.shader = sg_make_shader(gps_clear_shader_desc(sg_query_backend()));
        pd.label = "gps-clear-pipeline";
        r->gps_clear_pipeline = sg_make_pipeline(&pd);
    }
    {
        sg_pipeline_desc pd = {};
        pd.compute = true;
        pd.shader = sg_make_shader(gps_splat_shader_desc(sg_query_backend()));
        pd.label = "gps-splat-pipeline";
        r->gps_splat_pipeline = sg_make_pipeline(&pd);
    }
    {
        sg_pipeline_desc pd = {};
        pd.shader = sg_make_shader(gps_resolve_shader_desc(sg_query_backend()));
        pd.primitive_type = SG_PRIMITIVETYPE_TRIANGLES;
        pd.cull_mode = SG_CULLMODE_NONE;
        pd.depth.pixel_format = SG_PIXELFORMAT_NONE;
        pd.color_count = 2;
        pd.colors[0].pixel_format = SG_PIXELFORMAT_RGBA32F;
        pd.colors[0].blend.enabled = false;
        pd.colors[0].write_mask = SG_COLORMASK_RGBA;
        pd.colors[1].pixel_format = SG_PIXELFORMAT_R32F;
        pd.colors[1].blend.enabled = false;
        pd.colors[1].write_mask = SG_COLORMASK_R;
        pd.label = "gps-resolve-pipeline";
        r->gps_resolve_pipeline = sg_make_pipeline(&pd);
    }

    // --- Fullscreen accumulation/display pipelines ----------------------
    {
        sg_pipeline_desc pd = {};
        pd.shader = sg_make_shader(accum_shader_desc(sg_query_backend()));
        pd.primitive_type = SG_PRIMITIVETYPE_TRIANGLES;
        pd.cull_mode = SG_CULLMODE_NONE;
        pd.depth.pixel_format = SG_PIXELFORMAT_NONE;
        pd.colors[0].pixel_format = SG_PIXELFORMAT_RGBA32F;
        pd.colors[0].blend.enabled = false;
        pd.colors[0].write_mask = SG_COLORMASK_RGBA;
        pd.label = "stochastic-accum-pipeline";
        r->accum_pipeline = sg_make_pipeline(&pd);
    }
    {
        sg_pipeline_desc pd = {};
        pd.shader = sg_make_shader(taa_accum_shader_desc(sg_query_backend()));
        pd.primitive_type = SG_PRIMITIVETYPE_TRIANGLES;
        pd.cull_mode = SG_CULLMODE_NONE;
        pd.depth.pixel_format = SG_PIXELFORMAT_NONE;
        pd.color_count = 2;
        pd.colors[0].pixel_format = SG_PIXELFORMAT_RGBA32F;
        pd.colors[0].blend.enabled = false;
        pd.colors[0].write_mask = SG_COLORMASK_RGBA;
        pd.colors[1].pixel_format = SG_PIXELFORMAT_RGBA32F;
        pd.colors[1].blend.enabled = false;
        pd.colors[1].write_mask = SG_COLORMASK_RGBA;
        pd.label = "stochastic-taa-accum-pipeline";
        r->taa_accum_pipeline = sg_make_pipeline(&pd);
    }
    {
        sg_pipeline_desc pd = {};
        pd.shader = sg_make_shader(blit_shader_desc(sg_query_backend()));
        pd.primitive_type = SG_PRIMITIVETYPE_TRIANGLES;
        pd.cull_mode = SG_CULLMODE_NONE;
        pd.depth.pixel_format = SG_PIXELFORMAT_DEPTH_STENCIL;
        pd.colors[0].pixel_format = renderer_default_color_format();
        pd.colors[0].blend.enabled = false;
        pd.colors[0].write_mask = SG_COLORMASK_RGBA;
        pd.label = "stochastic-blit-pipeline";
        r->blit_pipeline = sg_make_pipeline(&pd);
    }

    // --- Overlay pipeline -----------------------------------------------
    {
        sg_pipeline_desc pd = {};
        pd.shader = sg_make_shader(overlay_shader_desc(sg_query_backend()));
        pd.primitive_type = SG_PRIMITIVETYPE_TRIANGLES;
        pd.cull_mode = SG_CULLMODE_NONE;
        pd.depth.pixel_format = SG_PIXELFORMAT_DEPTH_STENCIL;
        // Stencil: only draw where stencil != 1 (i.e. NOT inside the mesh
        // silhouette). Inside the mesh region, the mesh + splat composite
        // stays. ref value baked into the pipeline.
        pd.stencil.enabled = true;
        pd.stencil.read_mask = 0xFF;
        pd.stencil.write_mask = 0x00;
        pd.stencil.ref = 1;
        pd.stencil.front.compare = SG_COMPAREFUNC_NOT_EQUAL;
        pd.stencil.front.fail_op = SG_STENCILOP_KEEP;
        pd.stencil.front.depth_fail_op = SG_STENCILOP_KEEP;
        pd.stencil.front.pass_op = SG_STENCILOP_KEEP;
        pd.stencil.back = pd.stencil.front;
        pd.colors[0].pixel_format = renderer_default_color_format();
        pd.colors[0].blend.enabled = true;
        pd.colors[0].blend.src_factor_rgb = SG_BLENDFACTOR_ONE;
        pd.colors[0].blend.dst_factor_rgb = SG_BLENDFACTOR_ONE_MINUS_SRC_ALPHA;
        pd.colors[0].blend.op_rgb = SG_BLENDOP_ADD;
        pd.colors[0].blend.src_factor_alpha = SG_BLENDFACTOR_ONE;
        pd.colors[0].blend.dst_factor_alpha = SG_BLENDFACTOR_ONE_MINUS_SRC_ALPHA;
        pd.colors[0].blend.op_alpha = SG_BLENDOP_ADD;
        pd.colors[0].write_mask = (sg_color_mask)(SG_COLORMASK_R | SG_COLORMASK_G | SG_COLORMASK_B);
        pd.label = "overlay-pipeline";
        r->overlay_pipeline = sg_make_pipeline(&pd);
    }

    // --- Darken pipeline ------------------------------------------------
    // Fullscreen translucent black quad used to dim the FPS view behind the
    // top-down map overlay. Built even though the map_cam two-pass path is
    // disabled in this commit, so the pipeline is ready when it's restored.
    {
        sg_pipeline_desc pd = {};
        pd.shader = sg_make_shader(darken_shader_desc(sg_query_backend()));
        pd.primitive_type = SG_PRIMITIVETYPE_TRIANGLES;
        pd.cull_mode = SG_CULLMODE_NONE;
        pd.depth.pixel_format = SG_PIXELFORMAT_DEPTH_STENCIL;
        // No depth/stencil testing.
        pd.colors[0].pixel_format = renderer_default_color_format();
        pd.colors[0].blend.enabled = true;
        pd.colors[0].blend.src_factor_rgb = SG_BLENDFACTOR_ONE;
        pd.colors[0].blend.dst_factor_rgb = SG_BLENDFACTOR_ONE_MINUS_SRC_ALPHA;
        pd.colors[0].blend.op_rgb = SG_BLENDOP_ADD;
        pd.colors[0].blend.src_factor_alpha = SG_BLENDFACTOR_ONE;
        pd.colors[0].blend.dst_factor_alpha = SG_BLENDFACTOR_ONE_MINUS_SRC_ALPHA;
        pd.colors[0].blend.op_alpha = SG_BLENDOP_ADD;
        pd.colors[0].write_mask = (sg_color_mask)(SG_COLORMASK_R | SG_COLORMASK_G | SG_COLORMASK_B);
        pd.label = "darken-pipeline";
        r->darken_pipeline = sg_make_pipeline(&pd);
    }

    // --- Wireframe pipeline ---------------------------------------------
    {
        sg_pipeline_desc pd = {};
        pd.shader = sg_make_shader(wireframe_shader_desc(sg_query_backend()));
        pd.primitive_type = SG_PRIMITIVETYPE_LINES;
        pd.index_type = SG_INDEXTYPE_UINT16;
        pd.cull_mode = SG_CULLMODE_NONE;
        pd.layout.buffers[0].stride = 3 * sizeof(float);
        pd.layout.buffers[0].step_func = SG_VERTEXSTEP_PER_VERTEX;
        pd.layout.attrs[ATTR_wireframe_in_position].buffer_index = 0;
        pd.layout.attrs[ATTR_wireframe_in_position].offset = 0;
        pd.layout.attrs[ATTR_wireframe_in_position].format = SG_VERTEXFORMAT_FLOAT3;
        pd.depth.pixel_format = SG_PIXELFORMAT_DEPTH_STENCIL;
        pd.colors[0].pixel_format = renderer_default_color_format();
        pd.colors[0].blend.enabled = true;
        pd.colors[0].blend.src_factor_rgb = SG_BLENDFACTOR_ONE_MINUS_DST_ALPHA;
        pd.colors[0].blend.dst_factor_rgb = SG_BLENDFACTOR_ONE;
        pd.colors[0].blend.op_rgb = SG_BLENDOP_ADD;
        pd.colors[0].blend.src_factor_alpha = SG_BLENDFACTOR_ZERO;
        pd.colors[0].blend.dst_factor_alpha = SG_BLENDFACTOR_ONE;
        pd.colors[0].blend.op_alpha = SG_BLENDOP_ADD;
        pd.colors[0].write_mask = (sg_color_mask)(SG_COLORMASK_R | SG_COLORMASK_G | SG_COLORMASK_B);
        pd.label = "wireframe-pipeline";
        r->wireframe_pipeline = sg_make_pipeline(&pd);
    }

    // --- Mesh pipeline --------------------------------------------------
    {
        sg_pipeline_desc pd = {};
        pd.shader = sg_make_shader(mesh_shader_desc(sg_query_backend()));
        pd.primitive_type = SG_PRIMITIVETYPE_TRIANGLES;
        pd.index_type = SG_INDEXTYPE_UINT32;
        pd.cull_mode = SG_CULLMODE_BACK;
        pd.face_winding = SG_FACEWINDING_CW;
        pd.layout.buffers[0].stride = 5 * sizeof(float);   // vec3 pos + vec2 uv
        pd.layout.buffers[0].step_func = SG_VERTEXSTEP_PER_VERTEX;
        pd.layout.attrs[ATTR_mesh_in_position].buffer_index = 0;
        pd.layout.attrs[ATTR_mesh_in_position].offset = 0;
        pd.layout.attrs[ATTR_mesh_in_position].format = SG_VERTEXFORMAT_FLOAT3;
        pd.layout.attrs[ATTR_mesh_in_uv].buffer_index = 0;
        pd.layout.attrs[ATTR_mesh_in_uv].offset = 3 * sizeof(float);
        pd.layout.attrs[ATTR_mesh_in_uv].format = SG_VERTEXFORMAT_FLOAT2;
        pd.depth.compare = SG_COMPAREFUNC_LESS;
        pd.depth.write_enabled = true;
        pd.depth.pixel_format = SG_PIXELFORMAT_DEPTH_STENCIL;
        // Every mesh pixel writes 1 to stencil, marking the mesh region.
        // The overlay pass draws only where stencil != 1.
        pd.stencil.enabled = true;
        pd.stencil.read_mask = 0xFF;
        pd.stencil.write_mask = 0xFF;
        pd.stencil.ref = 1;
        pd.stencil.front.compare = SG_COMPAREFUNC_ALWAYS;
        pd.stencil.front.fail_op = SG_STENCILOP_KEEP;
        pd.stencil.front.depth_fail_op = SG_STENCILOP_KEEP;
        pd.stencil.front.pass_op = SG_STENCILOP_REPLACE;
        pd.stencil.back = pd.stencil.front;
        pd.colors[0].pixel_format = renderer_default_color_format();
        pd.colors[0].blend.enabled = false;
        pd.colors[0].write_mask = SG_COLORMASK_RGBA;
        pd.label = "mesh-pipeline";
        r->mesh_pipeline = sg_make_pipeline(&pd);
    }

    bool ok = r->splat_pipeline.id && r->splat_stochastic_pipeline.id &&
              r->cull_pipeline.id && r->cull_reset_pipeline.id &&
              r->gps_clear_pipeline.id && r->gps_splat_pipeline.id &&
              r->gps_resolve_pipeline.id &&
              r->accum_pipeline.id && r->taa_accum_pipeline.id &&
              r->blit_pipeline.id && r->overlay_pipeline.id &&
              r->darken_pipeline.id && r->wireframe_pipeline.id &&
              r->mesh_pipeline.id;
    if (!ok) {
        LOG(ERROR|RENDERER|SHADER, "renderer_create_shader_pipelines failed");
        renderer_destroy_shader_pipelines(r);
    }
    return ok;
}

bool renderer_reload_shaders(Renderer* r) {
    renderer_destroy_shader_pipelines(r);
    bool ok = renderer_create_shader_pipelines(r);
    if (ok) LOG(INFO|RENDERER|SHADER, "Renderer shaders reloaded");
    return ok;
}

bool renderer_init(Renderer* r) {
    memset(r, 0, sizeof(*r));
    r->splat_render_mode = SplatRenderMode::AlphaBlendSorted;
    r->stochastic_samples_per_frame = 1;
    r->stochastic_taa_current_samples = 4;
    r->stochastic_accumulation_enabled = true;
    r->stochastic_taa_enabled = true;
    r->sh_degree = 3;            // full SH degree 3 by default (lossless)
    r->sh_lod_distance = 0.0f;    // distance LOD off by default
    r->mesh_transform.scale = 1.0f;
    r->object_transform.scale = 1.0f;
    PROFILE_GPU_CONTEXT();

    if (!renderer_create_shader_pipelines(r)) {
        return false;
    }

    r->gps_capabilities = renderer_query_gps_capabilities();
    LOG(INFO|RENDERER|INIT,
        "GPS capabilities: compute=%d storage_images=%d shader_int64=%d atomic_min_64=%d supported=%d",
        r->gps_capabilities.compute ? 1 : 0,
        r->gps_capabilities.storage_images ? 1 : 0,
        r->gps_capabilities.shader_int64 ? 1 : 0,
        r->gps_capabilities.atomic_min_64 ? 1 : 0,
        r->gps_capabilities.supported ? 1 : 0);

    // --- Samplers -------------------------------------------------------
    {
        sg_sampler_desc sd = {};
        sd.min_filter = SG_FILTER_LINEAR;
        sd.mag_filter = SG_FILTER_LINEAR;
        sd.mipmap_filter = SG_FILTER_NEAREST;
        sd.wrap_u = SG_WRAP_REPEAT;
        sd.wrap_v = SG_WRAP_CLAMP_TO_EDGE;
        sd.wrap_w = SG_WRAP_CLAMP_TO_EDGE;
        sd.label = "overlay-sampler";
        r->overlay_sampler = sg_make_sampler(&sd);
    }
    {
        sg_sampler_desc sd = {};
        sd.min_filter = SG_FILTER_NEAREST;
        sd.mag_filter = SG_FILTER_NEAREST;
        sd.mipmap_filter = SG_FILTER_NEAREST;
        sd.wrap_u = SG_WRAP_REPEAT;
        sd.wrap_v = SG_WRAP_REPEAT;
        sd.wrap_w = SG_WRAP_REPEAT;
        sd.label = "mesh-sampler";
        r->mesh_sampler = sg_make_sampler(&sd);
    }
    {
        sg_sampler_desc sd = {};
        sd.min_filter = SG_FILTER_NEAREST;
        sd.mag_filter = SG_FILTER_NEAREST;
        sd.mipmap_filter = SG_FILTER_NEAREST;
        sd.wrap_u = SG_WRAP_CLAMP_TO_EDGE;
        sd.wrap_v = SG_WRAP_CLAMP_TO_EDGE;
        sd.wrap_w = SG_WRAP_CLAMP_TO_EDGE;
        sd.label = "accum-sampler";
        r->accum_sampler = sg_make_sampler(&sd);
    }

    // --- Cube geometry (unit cube centered at origin, ±0.5) -------------
    static const float cube_verts[8 * 3] = {
        -0.5f, -0.5f, -0.5f,
         0.5f, -0.5f, -0.5f,
         0.5f,  0.5f, -0.5f,
        -0.5f,  0.5f, -0.5f,
        -0.5f, -0.5f,  0.5f,
         0.5f, -0.5f,  0.5f,
         0.5f,  0.5f,  0.5f,
        -0.5f,  0.5f,  0.5f,
    };
    static const uint16_t cube_indices[24] = {
        0,1, 1,2, 2,3, 3,0,
        4,5, 5,6, 6,7, 7,4,
        0,4, 1,5, 2,6, 3,7,
    };
    {
        sg_buffer_desc bd = {};
        bd.usage.vertex_buffer = true;
        bd.data = SG_RANGE(cube_verts);
        bd.label = "cube-vb";
        r->cube_vertex_buffer = sg_make_buffer(&bd);
    }
    {
        sg_buffer_desc bd = {};
        bd.usage.index_buffer = true;
        bd.data = SG_RANGE(cube_indices);
        bd.label = "cube-ib";
        r->cube_index_buffer = sg_make_buffer(&bd);
    }

    LOG(INFO|RENDERER|INIT, "Renderer init OK");
    return true;
}

void renderer_upload_gaussians(Renderer* r, const GaussianScene* scene) {
    r->gaussian_count = scene->gaussian_count;
    r->sort_capacity = scene->gaussian_count;
    r->sort_group_count = (scene->gaussian_count + 255u) / 256u;
    renderer_reset_stochastic_accumulation(r);

    if (r->gaussian_buffer_view.id) {
        sg_destroy_view(r->gaussian_buffer_view);
        r->gaussian_buffer_view = {};
    }
    if (r->gaussian_buffer.id) {
        sg_destroy_buffer(r->gaussian_buffer);
        r->gaussian_buffer = {};
    }
    if (r->depth_key_buffer_view.id) {
        sg_destroy_view(r->depth_key_buffer_view);
        r->depth_key_buffer_view = {};
    }
    if (r->depth_key_buffer.id) {
        sg_destroy_buffer(r->depth_key_buffer);
        r->depth_key_buffer = {};
    }
    if (r->sort_temp_key_buffer_view.id) {
        sg_destroy_view(r->sort_temp_key_buffer_view);
        r->sort_temp_key_buffer_view = {};
    }
    if (r->sort_temp_key_buffer.id) {
        sg_destroy_buffer(r->sort_temp_key_buffer);
        r->sort_temp_key_buffer = {};
    }
    if (r->sort_temp_index_buffer_view.id) {
        sg_destroy_view(r->sort_temp_index_buffer_view);
        r->sort_temp_index_buffer_view = {};
    }
    if (r->sort_temp_index_buffer.id) {
        sg_destroy_buffer(r->sort_temp_index_buffer);
        r->sort_temp_index_buffer = {};
    }
    if (r->sort_histogram_buffer_view.id) {
        sg_destroy_view(r->sort_histogram_buffer_view);
        r->sort_histogram_buffer_view = {};
    }
    if (r->sort_histogram_buffer.id) {
        sg_destroy_buffer(r->sort_histogram_buffer);
        r->sort_histogram_buffer = {};
    }
    if (r->projected_splat_buffer_view.id) {
        sg_destroy_view(r->projected_splat_buffer_view);
        r->projected_splat_buffer_view = {};
    }
    if (r->projected_splat_buffer.id) {
        sg_destroy_buffer(r->projected_splat_buffer);
        r->projected_splat_buffer = {};
    }
    if (r->visible_count_buffer_view.id) {
        sg_destroy_view(r->visible_count_buffer_view);
        r->visible_count_buffer_view = {};
    }
    if (r->visible_count_buffer.id) {
        sg_destroy_buffer(r->visible_count_buffer);
        r->visible_count_buffer = {};
    }
    if (r->splat_diagnostics_buffer_view.id) {
        sg_destroy_view(r->splat_diagnostics_buffer_view);
        r->splat_diagnostics_buffer_view = {};
    }
    if (r->splat_diagnostics_buffer.id) {
        sg_destroy_buffer(r->splat_diagnostics_buffer);
        r->splat_diagnostics_buffer = {};
    }
    if (r->unsorted_index_buffer_view.id) {
        sg_destroy_view(r->unsorted_index_buffer_view);
        r->unsorted_index_buffer_view = {};
    }
    if (r->unsorted_index_buffer.id) {
        sg_destroy_buffer(r->unsorted_index_buffer);
        r->unsorted_index_buffer = {};
    }

    uint32_t payload_size = scene->gaussian_count * (uint32_t)sizeof(GpuGaussian);
    GpuGaussian* gpu_data = pack_gpu_gaussians(scene);

    sg_buffer_desc bd = {};
    bd.usage.storage_buffer = true;
    bd.size = payload_size;
    bd.data.ptr = gpu_data;
    bd.data.size = payload_size;
    bd.label = "gaussian-storage-buffer";
    r->gaussian_buffer = sg_make_buffer(&bd);
    free(gpu_data);

    if (sg_query_buffer_state(r->gaussian_buffer) != SG_RESOURCESTATE_VALID) {
        LOG(ERROR|GAUSSIAN|GPU, "gaussian-storage-buffer: allocation failed; splat drawing disabled");
        r->gaussian_count = 0;
        return;
    }

    sg_view_desc vd = {};
    vd.storage_buffer.buffer = r->gaussian_buffer;
    vd.label = "gaussian-storage-buffer-view";
    r->gaussian_buffer_view = sg_make_view(&vd);

    bd = {};
    bd.usage.storage_buffer = true;
    bd.size = r->sort_capacity * sizeof(uint32_t);
    bd.label = "splat-depth-key-storage-buffer";
    r->depth_key_buffer = sg_make_buffer(&bd);

    vd = {};
    vd.storage_buffer.buffer = r->depth_key_buffer;
    vd.label = "splat-depth-key-storage-buffer-view";
    r->depth_key_buffer_view = sg_make_view(&vd);

    bd = {};
    bd.usage.storage_buffer = true;
    bd.size = r->sort_capacity * sizeof(uint32_t);
    bd.label = "splat-sort-temp-key-storage-buffer";
    r->sort_temp_key_buffer = sg_make_buffer(&bd);

    vd = {};
    vd.storage_buffer.buffer = r->sort_temp_key_buffer;
    vd.label = "splat-sort-temp-key-storage-buffer-view";
    r->sort_temp_key_buffer_view = sg_make_view(&vd);

    bd = {};
    bd.usage.storage_buffer = true;
    bd.size = r->sort_capacity * sizeof(uint32_t);
    bd.label = "splat-sort-temp-index-storage-buffer";
    r->sort_temp_index_buffer = sg_make_buffer(&bd);

    vd = {};
    vd.storage_buffer.buffer = r->sort_temp_index_buffer;
    vd.label = "splat-sort-temp-index-storage-buffer-view";
    r->sort_temp_index_buffer_view = sg_make_view(&vd);

    bd = {};
    bd.usage.storage_buffer = true;
    bd.size = r->sort_group_count * 256u * sizeof(uint32_t);
    bd.label = "splat-sort-histogram-storage-buffer";
    r->sort_histogram_buffer = sg_make_buffer(&bd);

    vd = {};
    vd.storage_buffer.buffer = r->sort_histogram_buffer;
    vd.label = "splat-sort-histogram-storage-buffer-view";
    r->sort_histogram_buffer_view = sg_make_view(&vd);

    bd = {};
    bd.usage.storage_buffer = true;
    bd.size = scene->gaussian_count * sizeof(float) * 16u;
    bd.label = "projected-splat-storage-buffer";
    r->projected_splat_buffer = sg_make_buffer(&bd);

    vd = {};
    vd.storage_buffer.buffer = r->projected_splat_buffer;
    vd.label = "projected-splat-storage-buffer-view";
    r->projected_splat_buffer_view = sg_make_view(&vd);

    bd = {};
    bd.usage.storage_buffer = true;
    bd.size = sizeof(uint32_t);
    bd.label = "splat-visible-count-storage-buffer";
    r->visible_count_buffer = sg_make_buffer(&bd);

    vd = {};
    vd.storage_buffer.buffer = r->visible_count_buffer;
    vd.label = "splat-visible-count-storage-buffer-view";
    r->visible_count_buffer_view = sg_make_view(&vd);

    bd = {};
    bd.usage.storage_buffer = true;
    bd.size = sizeof(uint32_t) * 8u;
    bd.label = "splat-diagnostics-storage-buffer";
    r->splat_diagnostics_buffer = sg_make_buffer(&bd);

    vd = {};
    vd.storage_buffer.buffer = r->splat_diagnostics_buffer;
    vd.label = "splat-diagnostics-storage-buffer-view";
    r->splat_diagnostics_buffer_view = sg_make_view(&vd);

    // GPU-written per-instance unsorted visible-index buffer. Culled entries are
    // marked UINT_MAX; alpha mode sorts this buffer in place by depth.
    sg_buffer_desc ubd = {};
    ubd.usage.storage_buffer = true;
    ubd.size = r->sort_capacity * sizeof(uint32_t);
    ubd.label = "splat-unsorted-visible-index-storage-buffer";
    r->unsorted_index_buffer = sg_make_buffer(&ubd);

    vd = {};
    vd.storage_buffer.buffer = r->unsorted_index_buffer;
    vd.label = "splat-unsorted-visible-index-storage-buffer-view";
    r->unsorted_index_buffer_view = sg_make_view(&vd);

    LOG(INFO|GAUSSIAN|GPU, "Uploaded %u gaussians (storage buffer, %.1f MB)",
        scene->gaussian_count, (double)payload_size / (1024.0 * 1024.0));
}

static void renderer_read_splat_diagnostics(Renderer* r) {
    r->splat_diagnostics.valid = false;
    if (!r->splat_diagnostics_enabled || !r->splat_diagnostics_buffer.id) {
        return;
    }

#if defined(SOKOL_GLCORE)
    sg_gl_buffer_info info = sg_gl_query_buffer_info(r->splat_diagnostics_buffer);
    if (info.active_slot < 0 || info.active_slot >= SG_NUM_INFLIGHT_FRAMES || info.buf[info.active_slot] == 0) {
        return;
    }

    GLint previous_buffer = 0;
    glGetIntegerv(GL_SHADER_STORAGE_BUFFER_BINDING, &previous_buffer);
    glBindBuffer(GL_SHADER_STORAGE_BUFFER, info.buf[info.active_slot]);

    uint32_t stats[8] = {};
    glGetBufferSubData(GL_SHADER_STORAGE_BUFFER, 0, sizeof(stats), stats);

    glBindBuffer(GL_SHADER_STORAGE_BUFFER, (GLuint)previous_buffer);

    r->splat_diagnostics.total_quad_kpix = stats[0];
    r->splat_diagnostics.max_quad_px = stats[1];
    r->splat_diagnostics.splats_over_1k_px = stats[2];
    r->splat_diagnostics.splats_over_16k_px = stats[3];
    r->splat_diagnostics.total_gps_kpoints = stats[4];
    r->splat_diagnostics.max_gps_points = stats[5];
    r->splat_diagnostics.gps_splats_over_1k_points = stats[6];
    r->splat_diagnostics.gps_splats_over_16k_points = stats[7];
    r->splat_diagnostics.valid = true;
#endif
}

// Release everything held by a MeshGpu and zero it. Safe to call on an
// already-empty MeshGpu (all fields NULL/0).
static void mesh_gpu_release(MeshGpu* m) {
    if (m->vertex_buffer.id) sg_destroy_buffer(m->vertex_buffer);
    if (m->index_buffer.id)  sg_destroy_buffer(m->index_buffer);
    if (m->textures) {
        for (uint32_t i = 0; i < m->texture_count; ++i) {
            if (m->texture_views && m->texture_views[i].id) sg_destroy_view(m->texture_views[i]);
            if (m->textures[i].id) sg_destroy_image(m->textures[i]);
        }
        free(m->textures);
        free(m->texture_views);
    }
    if (m->default_texture_view.id) sg_destroy_view(m->default_texture_view);
    if (m->default_texture.id)      sg_destroy_image(m->default_texture);
    if (m->submeshes) free(m->submeshes);
    memset(m, 0, sizeof(*m));
}

// Upload mesh geometry, textures, and submesh metadata to `out`. Replaces any
// existing GPU resources in `out`. Returns true on success.
static bool mesh_gpu_upload(const Mesh* mesh, MeshGpu* out) {
    mesh_gpu_release(out);

    uint32_t vert_count  = mesh->vertex_count;
    uint32_t index_count = mesh->index_count;
    uint32_t vb_size = vert_count * 5 * sizeof(float); // vec3 pos + vec2 uv
    uint32_t ib_size = index_count * sizeof(uint32_t);

    {
        sg_buffer_desc bd = {};
        bd.usage.vertex_buffer = true;
        bd.data.ptr = mesh->vertices;
        bd.data.size = vb_size;
        bd.label = "mesh-vb";
        out->vertex_buffer = sg_make_buffer(&bd);
    }
    {
        sg_buffer_desc bd = {};
        bd.usage.index_buffer = true;
        bd.data.ptr = mesh->indices;
        bd.data.size = ib_size;
        bd.label = "mesh-ib";
        out->index_buffer = sg_make_buffer(&bd);
    }

    // Default 1x1 white texture (fallback for submeshes without a material).
    {
        static const uint8_t white_px[4] = { 255, 255, 255, 255 };
        sg_image_desc id = {};
        id.type = SG_IMAGETYPE_2D;
        id.width = 1;
        id.height = 1;
        id.num_slices = 1;
        id.num_mipmaps = 1;
        id.pixel_format = SG_PIXELFORMAT_RGBA8;
        id.data.mip_levels[0].ptr = white_px;
        id.data.mip_levels[0].size = sizeof(white_px);
        id.label = "mesh-default-tex";
        out->default_texture = sg_make_image(&id);

        sg_view_desc vd = {};
        vd.texture.image = out->default_texture;
        vd.label = "mesh-default-tex-view";
        out->default_texture_view = sg_make_view(&vd);
    }

    // Per-material textures.
    if (mesh->texture_count > 0) {
        out->textures = (sg_image*)calloc(mesh->texture_count, sizeof(sg_image));
        out->texture_views = (sg_view*)calloc(mesh->texture_count, sizeof(sg_view));
        out->texture_count = mesh->texture_count;
        for (uint32_t i = 0; i < mesh->texture_count; ++i) {
            const MeshTexture& mt = mesh->textures[i];
            sg_image_desc id = {};
            id.type = SG_IMAGETYPE_2D;
            id.width = mt.w;
            id.height = mt.h;
            id.num_slices = 1;
            id.num_mipmaps = 1;
            id.pixel_format = SG_PIXELFORMAT_RGBA8;
            id.data.mip_levels[0].ptr = mt.rgba;
            id.data.mip_levels[0].size = (size_t)mt.w * (size_t)mt.h * 4u;
            id.label = "mesh-tex";
            out->textures[i] = sg_make_image(&id);

            sg_view_desc vd = {};
            vd.texture.image = out->textures[i];
            vd.label = "mesh-tex-view";
            out->texture_views[i] = sg_make_view(&vd);
        }
    }

    // Copy submesh metadata.
    out->submesh_count = mesh->submesh_count;
    if (mesh->submesh_count > 0) {
        out->submeshes = (MeshSubmesh*)SDL_malloc(mesh->submesh_count * sizeof(MeshSubmesh));
        memcpy(out->submeshes, mesh->submeshes, mesh->submesh_count * sizeof(MeshSubmesh));
    }

    LOG(INFO|MESH|GPU, "Uploaded mesh: %u verts, %u indices, %u textures, %u submeshes",
        vert_count, index_count, mesh->texture_count, mesh->submesh_count);

    return true;
}

bool renderer_upload_mesh(Renderer* r, const Mesh* mesh) {
    return mesh_gpu_upload(mesh, &r->mesh_gpu);
}

bool renderer_upload_object_mesh(Renderer* r, const Mesh* mesh) {
    return mesh_gpu_upload(mesh, &r->object_gpu);
}

// Build column-major model matrix: T * Rz * Ry * Rx * S (intrinsic Z-Y-X Euler).
static void mat4_from_transform(const MeshTransform& t, float* out) {
    float cx = cosf(t.rotation_euler[0]), sx = sinf(t.rotation_euler[0]);
    float cy = cosf(t.rotation_euler[1]), sy = sinf(t.rotation_euler[1]);
    float cz = cosf(t.rotation_euler[2]), sz = sinf(t.rotation_euler[2]);
    float s = t.scale;

    float r00 = cy * cz;
    float r01 = sx * sy * cz - cx * sz;
    float r02 = cx * sy * cz + sx * sz;
    float r10 = cy * sz;
    float r11 = sx * sy * sz + cx * cz;
    float r12 = cx * sy * sz - sx * cz;
    float r20 = -sy;
    float r21 = sx * cy;
    float r22 = cx * cy;

    out[0]  = r00 * s; out[1]  = r10 * s; out[2]  = r20 * s; out[3]  = 0.0f;
    out[4]  = r01 * s; out[5]  = r11 * s; out[6]  = r21 * s; out[7]  = 0.0f;
    out[8]  = r02 * s; out[9]  = r12 * s; out[10] = r22 * s; out[11] = 0.0f;
    out[12] = t.translation[0];
    out[13] = t.translation[1];
    out[14] = t.translation[2];
    out[15] = 1.0f;
}

void renderer_reset_stochastic_accumulation(Renderer* r) {
    r->stochastic_sample_count = 0;
    r->stochastic_accum_write_index = 0;
    r->stochastic_prev_cam_valid = false;
    r->stochastic_prev_effect_valid = false;
    r->stochastic_taa_prev_view_proj_valid = false;
}

static void renderer_destroy_stochastic_targets(Renderer* r) {
    if (r->stochastic_sample_texture_view.id) sg_destroy_view(r->stochastic_sample_texture_view);
    if (r->stochastic_sample_color_view.id)   sg_destroy_view(r->stochastic_sample_color_view);
    if (r->stochastic_sample_image.id)        sg_destroy_image(r->stochastic_sample_image);
    if (r->stochastic_depth_texture_view.id)  sg_destroy_view(r->stochastic_depth_texture_view);
    if (r->stochastic_depth_view.id)          sg_destroy_view(r->stochastic_depth_view);
    if (r->stochastic_depth_image.id)         sg_destroy_image(r->stochastic_depth_image);
    for (int i = 0; i < 2; ++i) {
        if (r->stochastic_accum_texture_views[i].id) sg_destroy_view(r->stochastic_accum_texture_views[i]);
        if (r->stochastic_accum_color_views[i].id)   sg_destroy_view(r->stochastic_accum_color_views[i]);
        if (r->stochastic_accum_images[i].id)        sg_destroy_image(r->stochastic_accum_images[i]);
        r->stochastic_accum_texture_views[i] = {};
        r->stochastic_accum_color_views[i] = {};
        r->stochastic_accum_images[i] = {};
        if (r->stochastic_taa_xyz_texture_views[i].id) sg_destroy_view(r->stochastic_taa_xyz_texture_views[i]);
        if (r->stochastic_taa_xyz_color_views[i].id)   sg_destroy_view(r->stochastic_taa_xyz_color_views[i]);
        if (r->stochastic_taa_xyz_images[i].id)        sg_destroy_image(r->stochastic_taa_xyz_images[i]);
        r->stochastic_taa_xyz_texture_views[i] = {};
        r->stochastic_taa_xyz_color_views[i] = {};
        r->stochastic_taa_xyz_images[i] = {};
        if (r->stochastic_frame_avg_texture_views[i].id) sg_destroy_view(r->stochastic_frame_avg_texture_views[i]);
        if (r->stochastic_frame_avg_color_views[i].id)   sg_destroy_view(r->stochastic_frame_avg_color_views[i]);
        if (r->stochastic_frame_avg_images[i].id)        sg_destroy_image(r->stochastic_frame_avg_images[i]);
        r->stochastic_frame_avg_texture_views[i] = {};
        r->stochastic_frame_avg_color_views[i] = {};
        r->stochastic_frame_avg_images[i] = {};
    }
    r->stochastic_sample_texture_view = {};
    r->stochastic_sample_color_view = {};
    r->stochastic_sample_image = {};
    r->stochastic_depth_texture_view = {};
    r->stochastic_depth_view = {};
    r->stochastic_depth_image = {};
    r->stochastic_width = 0;
    r->stochastic_height = 0;
    renderer_reset_stochastic_accumulation(r);
}

static void gps_gpu_release(GaussianPointSplatGpu* gps) {
    if (gps->depth_key_buffer_view.id) sg_destroy_view(gps->depth_key_buffer_view);
    if (gps->depth_key_buffer.id)      sg_destroy_buffer(gps->depth_key_buffer);
    if (gps->color_buffer_view.id) sg_destroy_view(gps->color_buffer_view);
    if (gps->color_buffer.id)      sg_destroy_buffer(gps->color_buffer);
    if (gps->point_count_buffer_view.id) sg_destroy_view(gps->point_count_buffer_view);
    if (gps->point_count_buffer.id)      sg_destroy_buffer(gps->point_count_buffer);
    if (gps->point_offset_buffer_view.id) sg_destroy_view(gps->point_offset_buffer_view);
    if (gps->point_offset_buffer.id)      sg_destroy_buffer(gps->point_offset_buffer);
    if (gps->point_work_buffer_view.id) sg_destroy_view(gps->point_work_buffer_view);
    if (gps->point_work_buffer.id)      sg_destroy_buffer(gps->point_work_buffer);
    if (gps->atomic_color_depth_storage_view.id) sg_destroy_view(gps->atomic_color_depth_storage_view);
    if (gps->atomic_color_depth_image.id)        sg_destroy_image(gps->atomic_color_depth_image);
    if (gps->resolved_color_texture_view.id) sg_destroy_view(gps->resolved_color_texture_view);
    if (gps->resolved_color_view.id)         sg_destroy_view(gps->resolved_color_view);
    if (gps->resolved_color_image.id)        sg_destroy_image(gps->resolved_color_image);
    if (gps->resolved_depth_texture_view.id) sg_destroy_view(gps->resolved_depth_texture_view);
    if (gps->resolved_depth_view.id)         sg_destroy_view(gps->resolved_depth_view);
    if (gps->resolved_depth_image.id)        sg_destroy_image(gps->resolved_depth_image);
    *gps = {};
}

static sg_view make_texture_view(sg_image image, const char* label) {
    sg_view_desc vd = {};
    vd.texture.image = image;
    vd.label = label;
    return sg_make_view(&vd);
}

static sg_view make_color_attachment_view(sg_image image, const char* label) {
    sg_view_desc vd = {};
    vd.color_attachment.image = image;
    vd.label = label;
    return sg_make_view(&vd);
}

static bool renderer_ensure_gps_targets(Renderer* r, int width, int height) {
    if (width <= 0 || height <= 0) return false;

    GaussianPointSplatGpu* gps = &r->gps_gpu;
    if (gps->width == (uint32_t)width && gps->height == (uint32_t)height &&
        gps->depth_key_buffer.id && gps->color_buffer.id &&
        gps->resolved_color_image.id && gps->resolved_depth_image.id) {
        return true;
    }

    gps_gpu_release(gps);

    const uint32_t pixel_count = (uint32_t)width * (uint32_t)height;

    sg_buffer_desc bd = {};
    bd.usage.storage_buffer = true;
    bd.size = pixel_count * sizeof(uint32_t);
    bd.label = "gps-depth-key-buffer";
    gps->depth_key_buffer = sg_make_buffer(&bd);

    sg_view_desc vd = {};
    vd.storage_buffer.buffer = gps->depth_key_buffer;
    vd.label = "gps-depth-key-buffer-view";
    gps->depth_key_buffer_view = sg_make_view(&vd);

    bd = {};
    bd.usage.storage_buffer = true;
    bd.size = pixel_count * sizeof(uint32_t);
    bd.label = "gps-color-buffer";
    gps->color_buffer = sg_make_buffer(&bd);

    vd = {};
    vd.storage_buffer.buffer = gps->color_buffer;
    vd.label = "gps-color-buffer-view";
    gps->color_buffer_view = sg_make_view(&vd);

    sg_image_desc color_desc = {};
    color_desc.type = SG_IMAGETYPE_2D;
    color_desc.width = width;
    color_desc.height = height;
    color_desc.num_slices = 1;
    color_desc.num_mipmaps = 1;
    color_desc.pixel_format = SG_PIXELFORMAT_RGBA32F;
    color_desc.usage.color_attachment = true;
    color_desc.label = "gps-resolved-color";
    gps->resolved_color_image = sg_make_image(&color_desc);
    gps->resolved_color_view = make_color_attachment_view(gps->resolved_color_image, "gps-resolved-color-att-view");
    gps->resolved_color_texture_view = make_texture_view(gps->resolved_color_image, "gps-resolved-color-tex-view");

    sg_image_desc depth_desc = color_desc;
    depth_desc.pixel_format = SG_PIXELFORMAT_R32F;
    depth_desc.label = "gps-resolved-depth";
    gps->resolved_depth_image = sg_make_image(&depth_desc);
    gps->resolved_depth_view = make_color_attachment_view(gps->resolved_depth_image, "gps-resolved-depth-att-view");
    gps->resolved_depth_texture_view = make_texture_view(gps->resolved_depth_image, "gps-resolved-depth-tex-view");

    gps->width = (uint32_t)width;
    gps->height = (uint32_t)height;

    return gps->depth_key_buffer_view.id && gps->color_buffer_view.id &&
           gps->resolved_color_view.id && gps->resolved_color_texture_view.id &&
           gps->resolved_depth_view.id && gps->resolved_depth_texture_view.id;
}

static bool renderer_ensure_stochastic_targets(Renderer* r, int width, int height) {
    if (width <= 0 || height <= 0) return false;
    if (r->stochastic_width == (uint32_t)width && r->stochastic_height == (uint32_t)height &&
        r->stochastic_sample_image.id && r->stochastic_depth_image.id &&
        r->stochastic_accum_images[0].id && r->stochastic_accum_images[1].id &&
        r->stochastic_taa_xyz_images[0].id && r->stochastic_taa_xyz_images[1].id &&
        r->stochastic_frame_avg_images[0].id && r->stochastic_frame_avg_images[1].id) {
        return true;
    }

    renderer_destroy_stochastic_targets(r);

    sg_image_desc color_desc = {};
    color_desc.type = SG_IMAGETYPE_2D;
    color_desc.usage.color_attachment = true;
    color_desc.width = width;
    color_desc.height = height;
    color_desc.num_slices = 1;
    color_desc.num_mipmaps = 1;
    color_desc.pixel_format = renderer_default_color_format();
    color_desc.sample_count = 1;

    color_desc.label = "stochastic-sample-color";
    r->stochastic_sample_image = sg_make_image(&color_desc);
    r->stochastic_sample_color_view = make_color_attachment_view(r->stochastic_sample_image, "stochastic-sample-color-att-view");
    r->stochastic_sample_texture_view = make_texture_view(r->stochastic_sample_image, "stochastic-sample-tex-view");

    color_desc.pixel_format = SG_PIXELFORMAT_RGBA32F;
    for (int i = 0; i < 2; ++i) {
        color_desc.label = i == 0 ? "stochastic-accum-a" : "stochastic-accum-b";
        r->stochastic_accum_images[i] = sg_make_image(&color_desc);
        r->stochastic_accum_color_views[i] = make_color_attachment_view(r->stochastic_accum_images[i], i == 0 ? "stochastic-accum-a-att-view" : "stochastic-accum-b-att-view");
        r->stochastic_accum_texture_views[i] = make_texture_view(r->stochastic_accum_images[i], i == 0 ? "stochastic-accum-a-tex-view" : "stochastic-accum-b-tex-view");

        color_desc.label = i == 0 ? "stochastic-taa-xyz-a" : "stochastic-taa-xyz-b";
        r->stochastic_taa_xyz_images[i] = sg_make_image(&color_desc);
        r->stochastic_taa_xyz_color_views[i] = make_color_attachment_view(r->stochastic_taa_xyz_images[i], i == 0 ? "stochastic-taa-xyz-a-att-view" : "stochastic-taa-xyz-b-att-view");
        r->stochastic_taa_xyz_texture_views[i] = make_texture_view(r->stochastic_taa_xyz_images[i], i == 0 ? "stochastic-taa-xyz-a-tex-view" : "stochastic-taa-xyz-b-tex-view");

        color_desc.label = i == 0 ? "stochastic-frame-avg-a" : "stochastic-frame-avg-b";
        r->stochastic_frame_avg_images[i] = sg_make_image(&color_desc);
        r->stochastic_frame_avg_color_views[i] = make_color_attachment_view(r->stochastic_frame_avg_images[i], i == 0 ? "stochastic-frame-avg-a-att-view" : "stochastic-frame-avg-b-att-view");
        r->stochastic_frame_avg_texture_views[i] = make_texture_view(r->stochastic_frame_avg_images[i], i == 0 ? "stochastic-frame-avg-a-tex-view" : "stochastic-frame-avg-b-tex-view");
    }

    sg_image_desc depth_desc = {};
    depth_desc.type = SG_IMAGETYPE_2D;
    depth_desc.usage.depth_stencil_attachment = true;
    depth_desc.width = width;
    depth_desc.height = height;
    depth_desc.num_slices = 1;
    depth_desc.num_mipmaps = 1;
    depth_desc.pixel_format = SG_PIXELFORMAT_DEPTH_STENCIL;
    depth_desc.sample_count = 1;
    depth_desc.label = "stochastic-depth-stencil";
    r->stochastic_depth_image = sg_make_image(&depth_desc);

    sg_view_desc dvd = {};
    dvd.depth_stencil_attachment.image = r->stochastic_depth_image;
    dvd.label = "stochastic-depth-stencil-att-view";
    r->stochastic_depth_view = sg_make_view(&dvd);
    r->stochastic_depth_texture_view = make_texture_view(r->stochastic_depth_image, "stochastic-depth-tex-view");

    r->stochastic_width = (uint32_t)width;
    r->stochastic_height = (uint32_t)height;
    renderer_reset_stochastic_accumulation(r);

    return r->stochastic_sample_image.id && r->stochastic_sample_color_view.id &&
           r->stochastic_sample_texture_view.id && r->stochastic_depth_image.id &&
           r->stochastic_depth_view.id && r->stochastic_depth_texture_view.id &&
           r->stochastic_accum_images[0].id &&
           r->stochastic_accum_images[1].id && r->stochastic_accum_color_views[0].id &&
           r->stochastic_accum_color_views[1].id && r->stochastic_accum_texture_views[0].id &&
           r->stochastic_accum_texture_views[1].id &&
           r->stochastic_taa_xyz_images[0].id && r->stochastic_taa_xyz_images[1].id &&
           r->stochastic_taa_xyz_color_views[0].id && r->stochastic_taa_xyz_color_views[1].id &&
           r->stochastic_taa_xyz_texture_views[0].id && r->stochastic_taa_xyz_texture_views[1].id &&
           r->stochastic_frame_avg_images[0].id && r->stochastic_frame_avg_images[1].id &&
           r->stochastic_frame_avg_color_views[0].id && r->stochastic_frame_avg_color_views[1].id &&
           r->stochastic_frame_avg_texture_views[0].id && r->stochastic_frame_avg_texture_views[1].id;
}

// Draws mesh + splats + (optional) panorama overlay + (optional) wireframe
// nodes for one camera into the currently-active sg_begin_pass. ImGui is NOT
// drawn here; the caller is responsible for that after this returns.
static void draw_world(Renderer* r, const GaussianScene* scene, const CameraUniforms* cam,
                       const OverlayParams* overlay, const NodeRenderParams* nodes,
                       const SplatEffectParams* splat_effect, SplatRenderMode splat_mode,
                       const float* splat_jitter_px = NULL) {
    (void)splat_effect;
    // VP shared by both mesh slots and the wireframe pass.
    float vp[16];
    math_mat4_mul(cam->proj, cam->view, vp);

    // Mesh: writes color, depth, and stencil=1 to mark its silhouette. Same
    // lambda is reused for the static --object mesh (with its own MVP).
    auto draw_mesh_slot = [&](const MeshGpu* m, const float* mvp) {
        if (m->vertex_buffer.id == 0 || m->index_buffer.id == 0 || m->submesh_count == 0) return;

        sg_apply_pipeline(r->mesh_pipeline);

        for (uint32_t i = 0; i < m->submesh_count; ++i) {
            const MeshSubmesh& sm = m->submeshes[i];
            if (sm.index_count == 0) continue;

            sg_view tex_view = m->default_texture_view;
            float use_texture = 0.0f;
            if (sm.texture_id >= 0 && (uint32_t)sm.texture_id < m->texture_count
                && m->textures[sm.texture_id].id) {
                tex_view = m->texture_views[sm.texture_id];
                use_texture = 1.0f;
            }

            sg_bindings bnd = {};
            bnd.vertex_buffers[0] = m->vertex_buffer;
            bnd.index_buffer = m->index_buffer;
            bnd.views[VIEW_mesh_tex] = tex_view;
            bnd.samplers[SMP_mesh_smp] = r->mesh_sampler;
            sg_apply_bindings(&bnd);

            MeshUniforms_t u = {};
            memcpy(u.mvp, mvp, sizeof(u.mvp));
            u.color[0] = u.color[1] = u.color[2] = u.color[3] = 1.0f;
            u.use_texture = use_texture;
            sg_apply_uniforms(UB_MeshUniforms, SG_RANGE_REF(u));

            sg_draw((int)sm.index_offset, (int)sm.index_count, 1);
        }
    };

    PROFILE("render mesh pass") {
    PROFILE_GPU_BEGIN("mesh pass");
    // Primary animated mesh.
    {
        float model[16];
        mat4_from_transform(r->mesh_transform, model);
        float mvp[16];
        math_mat4_mul(vp, model, mvp);
        draw_mesh_slot(&r->mesh_gpu, mvp);
    }

    // Static --object mesh (transformed by object_transform; identity by default).
    if (r->object_gpu.vertex_buffer.id) {
        float obj_model[16];
        mat4_from_transform(r->object_transform, obj_model);
        float obj_mvp[16];
        math_mat4_mul(vp, obj_model, obj_mvp);
        draw_mesh_slot(&r->object_gpu, obj_mvp);
    }
    PROFILE_GPU_END();
    }

    // Splats
    sg_view splat_id_buffer_view = r->unsorted_index_buffer_view;
    if (scene->visible_count > 0 && r->projected_splat_buffer_view.id && splat_id_buffer_view.id) {
        PROFILE("render splat pass") {
        PROFILE_GPU("splat pass") {
        sg_apply_pipeline(splat_mode == SplatRenderMode::StochasticSplats
            ? r->splat_stochastic_pipeline
            : r->splat_pipeline);

        sg_bindings bnd = {};
        bnd.views[VIEW_ProjectedSplatBuffer] = r->projected_splat_buffer_view;
        bnd.views[VIEW_SplatIdBuffer] = splat_id_buffer_view;
        sg_apply_bindings(&bnd);

        SplatDrawUBO_t draw_ubo = {};
        draw_ubo.viewport[0] = cam->viewport[0];
        draw_ubo.viewport[1] = cam->viewport[1];
        if (splat_jitter_px) {
            draw_ubo.jitter_px[0] = splat_jitter_px[0];
            draw_ubo.jitter_px[1] = splat_jitter_px[1];
        }
        draw_ubo.clip_y_sign = cam->clip_y_sign;
        sg_apply_uniforms(UB_SplatDrawUBO, SG_RANGE_REF(draw_ubo));
        if (splat_mode == SplatRenderMode::StochasticSplats) {
            StochasticUBO_t stochastic_ubo = {};
            stochastic_ubo.frame_seed = (float)r->stochastic_frame_seed;
            sg_apply_uniforms(UB_StochasticUBO, SG_RANGE_REF(stochastic_ubo));
        }

        // 6 vertices per quad, scene->visible_count instances.
        sg_draw(0, 6, (int)scene->visible_count);
        }
        }
    }

    // Equirectangular panorama overlay.
    if (overlay && overlay->texture.id && overlay->alpha > 0.0f) {
        PROFILE("render overlay pass") {
        PROFILE_GPU("overlay pass") {
        sg_apply_pipeline(r->overlay_pipeline);

        sg_bindings bnd = {};
        bnd.views[VIEW_panorama_tex] = overlay->texture_view;
        bnd.samplers[SMP_panorama_smp] = r->overlay_sampler;
        sg_apply_bindings(&bnd);

        OverlayUniforms_t u = {};
        memcpy(u.camera_ray_basis, overlay->camera_ray_basis, sizeof(u.camera_ray_basis));
        memcpy(u.camera_tan_half_fov, overlay->camera_tan_half_fov, sizeof(u.camera_tan_half_fov));
        memcpy(u.ref_rotation, overlay->ref_rotation, sizeof(u.ref_rotation));
        u.alpha = overlay->alpha;
        sg_apply_uniforms(UB_OverlayUniforms, SG_RANGE_REF(u));

        sg_draw(0, 3, 1); // fullscreen triangle
        }
        }
    }

    // Wireframe node cubes.
    if (nodes && nodes->count > 0) {
        PROFILE("render wireframe pass") {
        PROFILE_GPU("wireframe pass") {
        sg_apply_pipeline(r->wireframe_pipeline);

        float scale = nodes->half_size * 2.0f;
        for (uint32_t i = 0; i < nodes->count; i++) {
            const float* p = &nodes->positions[i * 3];

            sg_bindings bnd = {};
            bnd.vertex_buffers[0] = r->cube_vertex_buffer;
            bnd.index_buffer = r->cube_index_buffer;
            sg_apply_bindings(&bnd);

            float model[16];
            math_mat4_translate_scale(p[0], p[1], p[2], scale, model);
            float mvp[16];
            math_mat4_mul(vp, model, mvp);

            WireframeUniforms_t u = {};
            memcpy(u.mvp, mvp, sizeof(u.mvp));
            u.color[0] = 0.0f; u.color[1] = 1.0f; u.color[2] = 1.0f; u.color[3] = 1.0f;
            sg_apply_uniforms(UB_WireframeUniforms, SG_RANGE_REF(u));

            sg_draw(0, 24, 1);
        }
        }
        }
    }
}

static void renderer_cull_gaussians_gpu(Renderer* r, GaussianScene* scene, const CameraUniforms* cam,
                                        const SplatEffectParams* splat_effect) {
    if (!r->cull_pipeline.id || !r->gaussian_buffer_view.id ||
        !r->unsorted_index_buffer_view.id || !r->depth_key_buffer_view.id ||
        !r->projected_splat_buffer_view.id ||
        !r->visible_count_buffer_view.id ||
        scene->gaussian_count == 0) {
        scene->visible_count = 0;
        return;
    }

    {
        sg_pass pass = {};
        pass.compute = true;
        sg_begin_pass(&pass);
        sg_apply_pipeline(r->cull_reset_pipeline);

        sg_bindings bnd = {};
        bnd.views[VIEW_ResetVisibleCount] = r->visible_count_buffer_view;
        bnd.views[VIEW_ResetOutputSplatIds] = r->unsorted_index_buffer_view;
        bnd.views[VIEW_ResetDepthKeys] = r->depth_key_buffer_view;
        bnd.views[VIEW_ResetSplatDiagnostics] = r->splat_diagnostics_buffer_view;
        sg_apply_bindings(&bnd);

        ResetUBO_t u = {};
        u.sort_count = r->sort_capacity;
        sg_apply_uniforms(UB_ResetUBO, SG_RANGE_REF(u));

        sg_dispatch((int)((r->sort_capacity + 255u) / 256u), 1, 1);
        sg_end_pass();
    }

    sg_pass pass = {};
    pass.compute = true;
    sg_begin_pass(&pass);
    sg_apply_pipeline(r->cull_pipeline);

    sg_bindings bnd = {};
    bnd.views[VIEW_GaussianBuffer] = r->gaussian_buffer_view;
    bnd.views[VIEW_OutputSplatIds] = r->unsorted_index_buffer_view;
    bnd.views[VIEW_OutputDepthKeys] = r->depth_key_buffer_view;
    bnd.views[VIEW_ProjectedSplats] = r->projected_splat_buffer_view;
    bnd.views[VIEW_VisibleCount] = r->visible_count_buffer_view;
    bnd.views[VIEW_SplatDiagnostics] = r->splat_diagnostics_buffer_view;
    sg_apply_bindings(&bnd);

    CullUBO_t u = {};
    memcpy(u.view, cam->view, sizeof(u.view));
    memcpy(u.proj, cam->proj, sizeof(u.proj));
    u.viewport[0] = cam->viewport[0];
    u.viewport[1] = cam->viewport[1];
    u.gaussian_count = scene->gaussian_count;
    u.orthographic = cam->orthographic;
    u.persp_focal = cam->persp_focal;
    u.ortho_focal = cam->ortho_focal;
    u.clip_y_sign = cam->clip_y_sign;
    u.clip_z_01 = cam->clip_z_01;
    u.collect_stats = r->splat_diagnostics_enabled ? 1 : 0;
    u.sh_degree = r->sh_degree;
    u.sh_lod_distance = r->sh_lod_distance;
    sg_apply_uniforms(UB_CullUBO, SG_RANGE_REF(u));

    SplatEffectUBO_t effect_ubo = {};
    if (splat_effect) {
        memcpy(effect_ubo.effect_center_radius, splat_effect->center_radius, sizeof(effect_ubo.effect_center_radius));
        memcpy(effect_ubo.effect_params, splat_effect->params, sizeof(effect_ubo.effect_params));
        memcpy(effect_ubo.effect_color, splat_effect->color, sizeof(effect_ubo.effect_color));
    }
    sg_apply_uniforms(UB_SplatEffectUBO, SG_RANGE_REF(effect_ubo));

    sg_dispatch((int)((scene->gaussian_count + 255u) / 256u), 1, 1);
    sg_end_pass();

    renderer_read_splat_diagnostics(r);

}

static void renderer_sort_gaussians_gpu(Renderer* r) {
    if (!r->radix_hist_pipeline.id || !r->radix_prefix_pipeline.id || !r->radix_scatter_pipeline.id ||
        !r->depth_key_buffer_view.id || !r->unsorted_index_buffer_view.id ||
        !r->sort_temp_key_buffer_view.id || !r->sort_temp_index_buffer_view.id ||
        !r->sort_histogram_buffer_view.id || r->sort_capacity <= 1u || r->sort_group_count == 0u) {
        return;
    }

    sg_view key_views[2] = { r->depth_key_buffer_view, r->sort_temp_key_buffer_view };
    sg_view id_views[2] = { r->unsorted_index_buffer_view, r->sort_temp_index_buffer_view };

    for (uint32_t pass_i = 0; pass_i < 4u; ++pass_i) {
        const int shift = (int)(pass_i * 8u);
        const uint32_t src = pass_i & 1u;
        const uint32_t dst = src ^ 1u;

        {
            PROFILE("radix hist") {
            PROFILE_GPU("radix hist") {
            sg_pass pass = {};
            pass.compute = true;
            sg_begin_pass(&pass);
            sg_apply_pipeline(r->radix_hist_pipeline);

            sg_bindings bnd = {};
            bnd.views[VIEW_RadixHistKeys] = key_views[src];
            bnd.views[VIEW_RadixHistograms] = r->sort_histogram_buffer_view;
            sg_apply_bindings(&bnd);

            RadixHistUBO_t u = {};
            u.sort_count = (int)r->sort_capacity;
            u.shift = shift;
            sg_apply_uniforms(UB_RadixHistUBO, SG_RANGE_REF(u));

            sg_dispatch((int)r->sort_group_count, 1, 1);
            sg_end_pass();
            }
            }
        }

        {
            PROFILE("radix prefix") {
            PROFILE_GPU("radix prefix") {
            sg_pass pass = {};
            pass.compute = true;
            sg_begin_pass(&pass);
            sg_apply_pipeline(r->radix_prefix_pipeline);

            sg_bindings bnd = {};
            bnd.views[VIEW_RadixPrefixHistograms] = r->sort_histogram_buffer_view;
            sg_apply_bindings(&bnd);

            RadixPrefixUBO_t u = {};
            u.group_count = (int)r->sort_group_count;
            sg_apply_uniforms(UB_RadixPrefixUBO, SG_RANGE_REF(u));

            sg_dispatch(1, 1, 1);
            sg_end_pass();
            }
            }
        }

        {
            PROFILE("radix scatter") {
            PROFILE_GPU("radix scatter") {
            sg_pass pass = {};
            pass.compute = true;
            sg_begin_pass(&pass);
            sg_apply_pipeline(r->radix_scatter_pipeline);

            sg_bindings bnd = {};
            bnd.views[VIEW_RadixScatterKeysIn] = key_views[src];
            bnd.views[VIEW_RadixScatterKeysOut] = key_views[dst];
            bnd.views[VIEW_RadixScatterIdsIn] = id_views[src];
            bnd.views[VIEW_RadixScatterIdsOut] = id_views[dst];
            bnd.views[VIEW_RadixScatterHistograms] = r->sort_histogram_buffer_view;
            sg_apply_bindings(&bnd);

            RadixScatterUBO_t u = {};
            u.sort_count = (int)r->sort_capacity;
            u.shift = shift;
            sg_apply_uniforms(UB_RadixScatterUBO, SG_RANGE_REF(u));

            sg_dispatch((int)r->sort_group_count, 1, 1);
            sg_end_pass();
            }
            }
        }
    }
}

static bool renderer_draw_gps_sample(Renderer* r, const GaussianScene* scene, const CameraUniforms* cam) {
    GaussianPointSplatGpu* gps = &r->gps_gpu;
    const uint32_t pixel_count = gps->width * gps->height;
    if (pixel_count == 0 || !r->gps_clear_pipeline.id || !r->gps_splat_pipeline.id ||
        !r->gps_resolve_pipeline.id || !gps->depth_key_buffer_view.id ||
        !gps->color_buffer_view.id || !r->projected_splat_buffer_view.id ||
        !r->unsorted_index_buffer_view.id) {
        return false;
    }

    {
        sg_pass pass = {};
        pass.compute = true;
        sg_begin_pass(&pass);
        sg_apply_pipeline(r->gps_clear_pipeline);
        sg_bindings bnd = {};
        bnd.views[VIEW_GpsClearDepthKeys] = gps->depth_key_buffer_view;
        bnd.views[VIEW_GpsClearColors] = gps->color_buffer_view;
        sg_apply_bindings(&bnd);
        GpsClearUBO_t u = {};
        u.pixel_count = (int)pixel_count;
        sg_apply_uniforms(UB_GpsClearUBO, SG_RANGE_REF(u));
        sg_dispatch((int)((pixel_count + 255u) / 256u), 1, 1);
        sg_end_pass();
    }

    if (scene->gaussian_count > 0) {
        sg_pass pass = {};
        pass.compute = true;
        sg_begin_pass(&pass);
        sg_apply_pipeline(r->gps_splat_pipeline);
        sg_bindings bnd = {};
        bnd.views[VIEW_GpsProjectedSplatBuffer] = r->projected_splat_buffer_view;
        bnd.views[VIEW_GpsSplatIdBuffer] = r->unsorted_index_buffer_view;
        bnd.views[VIEW_GpsDepthKeys] = gps->depth_key_buffer_view;
        bnd.views[VIEW_GpsColors] = gps->color_buffer_view;
        sg_apply_bindings(&bnd);
        GpsSplatUBO_t u = {};
        u.viewport[0] = cam->viewport[0];
        u.viewport[1] = cam->viewport[1];
        u.gaussian_count = (int)scene->gaussian_count;
        u.clip_z_01 = cam->clip_z_01;
        sg_apply_uniforms(UB_GpsSplatUBO, SG_RANGE_REF(u));
        sg_dispatch((int)((scene->gaussian_count + 255u) / 256u), 1, 1);
        sg_end_pass();
    }

    sg_pass pass = {};
    pass.action.colors[0].load_action = SG_LOADACTION_DONTCARE;
    pass.action.colors[0].store_action = SG_STOREACTION_STORE;
    pass.action.colors[1].load_action = SG_LOADACTION_DONTCARE;
    pass.action.colors[1].store_action = SG_STOREACTION_STORE;
    pass.attachments.colors[0] = gps->resolved_color_view;
    pass.attachments.colors[1] = gps->resolved_depth_view;
    sg_begin_pass(&pass);
    sg_apply_pipeline(r->gps_resolve_pipeline);
    sg_bindings bnd = {};
    bnd.views[VIEW_GpsResolveDepthKeys] = gps->depth_key_buffer_view;
    bnd.views[VIEW_GpsResolveColors] = gps->color_buffer_view;
    sg_apply_bindings(&bnd);
    GpsResolveUBO_t u = {};
    u.viewport[0] = cam->viewport[0];
    u.viewport[1] = cam->viewport[1];
    sg_apply_uniforms(UB_GpsResolveUBO, SG_RANGE_REF(u));
    sg_draw(0, 3, 1);
    sg_end_pass();

    return true;
}

void renderer_draw_frame(Renderer* r, GaussianScene* scene, const CameraUniforms* cam,
                         const OverlayParams* overlay, const NodeRenderParams* nodes,
                         const SplatEffectParams* splat_effect,
                         float wireframe_occlusion, const CameraUniforms* map_cam) {
    (void)wireframe_occlusion; // see splat-pipeline blend comment in renderer_init
    (void)map_cam;             // TODO: restore the two-pass top-down map overlay in a later commit

    const bool stochastic = (r->splat_render_mode == SplatRenderMode::StochasticSplats);
    const bool gps = (r->splat_render_mode == SplatRenderMode::GaussianPointSplatting);

    if (scene->gaussian_count > 0) {
        PROFILE("gaussian gpu cull/project") {
        PROFILE_GPU("gaussian gpu cull/project") {
        renderer_cull_gaussians_gpu(r, scene, cam, splat_effect);
        }
        }
        if (stochastic || gps) {
            // Sokol doesn't expose an indirect draw count here, so stochastic
            // modes draw one instance per gaussian; the shader skips UINT_MAX
            // entries written by the cull/project pass.
            scene->visible_count = scene->gaussian_count;
        } else {
            PROFILE("gaussian gpu sort") {
            PROFILE_GPU("gaussian gpu sort") {
            renderer_sort_gaussians_gpu(r);
            }
            }
            // Sokol doesn't expose an indirect draw count here, so alpha mode
            // draws one sorted entry per gaussian; the shader skips culled
            // UINT_MAX entries.
            scene->visible_count = scene->gaussian_count;
        }
    }

    int win_w = sapp_width();
    int win_h = sapp_height();

    if (gps) {
        if (!r->gps_capabilities.compute || !renderer_ensure_stochastic_targets(r, win_w, win_h) ||
            !renderer_ensure_gps_targets(r, win_w, win_h)) {
            LOG(ERROR|RENDERER|RESOURCE, "Failed to create GPS prototype targets");
            return;
        }

        if (r->stochastic_prev_cam_valid && memcmp(&r->stochastic_prev_cam, cam, sizeof(*cam)) != 0) {
            renderer_reset_stochastic_accumulation(r);
        }
        memcpy(&r->stochastic_prev_cam, cam, sizeof(*cam));
        r->stochastic_prev_cam_valid = true;

        if (!renderer_draw_gps_sample(r, scene, cam)) {
            LOG(ERROR|RENDERER|RESOURCE, "Failed to draw GPS prototype sample");
            return;
        }

        uint32_t write_index = r->stochastic_accum_write_index & 1u;
        uint32_t read_index = (write_index + 1u) & 1u;
        uint32_t next_sample_count = r->stochastic_sample_count + 1u;

        sg_pass accum_pass = {};
        accum_pass.action.colors[0].load_action = (next_sample_count == 1u) ? SG_LOADACTION_CLEAR : SG_LOADACTION_DONTCARE;
        accum_pass.action.colors[0].store_action = SG_STOREACTION_STORE;
        accum_pass.action.colors[0].clear_value = { 0.1f, 0.1f, 0.1f, 0.0f };
        accum_pass.attachments.colors[0] = r->stochastic_accum_color_views[write_index];
        sg_begin_pass(&accum_pass);
        sg_apply_pipeline(r->accum_pipeline);
        sg_bindings accum_bnd = {};
        accum_bnd.views[VIEW_sample_tex] = r->gps_gpu.resolved_color_texture_view;
        accum_bnd.samplers[SMP_sample_smp] = r->accum_sampler;
        accum_bnd.views[VIEW_history_tex] = (next_sample_count == 1u)
            ? r->gps_gpu.resolved_color_texture_view
            : r->stochastic_accum_texture_views[read_index];
        accum_bnd.samplers[SMP_history_smp] = r->accum_sampler;
        sg_apply_bindings(&accum_bnd);
        AccumUBO_t accum_ubo = {};
        accum_ubo.sample_count = (float)next_sample_count;
        sg_apply_uniforms(UB_AccumUBO, SG_RANGE_REF(accum_ubo));
        sg_draw(0, 3, 1);
        sg_end_pass();

        r->stochastic_sample_count = next_sample_count;
        r->stochastic_accum_write_index = (write_index + 1u) & 1u;

        sg_pass pass = {};
        pass.action.colors[0].load_action = SG_LOADACTION_CLEAR;
        pass.action.colors[0].store_action = SG_STOREACTION_STORE;
        pass.action.colors[0].clear_value = { 0.1f, 0.1f, 0.1f, 0.0f };
        pass.swapchain = sglue_swapchain();

        sg_begin_pass(&pass);
        sg_apply_pipeline(r->blit_pipeline);
        sg_bindings blit_bnd = {};
        blit_bnd.views[VIEW_display_tex] = r->stochastic_accum_texture_views[write_index];
        blit_bnd.samplers[SMP_display_smp] = r->accum_sampler;
        sg_apply_bindings(&blit_bnd);
        sg_draw(0, 3, 1);
        PROFILE("render imgui pass") {
        PROFILE_GPU("imgui pass") {
        simgui_render();
        }
        }
        sg_end_pass();
        PROFILE("render commit") {
        sg_commit();
        PROFILE_GPU_COLLECT();
        }
        return;
    }

    if (stochastic) {
        if (!renderer_ensure_stochastic_targets(r, win_w, win_h)) {
            LOG(ERROR|RENDERER|RESOURCE, "Failed to create stochastic render targets");
            return;
        }

        SplatEffectParams empty_effect = {};
        const SplatEffectParams* effect_for_compare = splat_effect ? splat_effect : &empty_effect;
        CameraUniforms prev_cam = r->stochastic_prev_cam;
        bool prev_cam_valid = r->stochastic_prev_cam_valid;
        bool cam_changed = r->stochastic_prev_cam_valid && memcmp(&r->stochastic_prev_cam, cam, sizeof(*cam)) != 0;
        bool effect_changed = r->stochastic_prev_effect_valid && memcmp(&r->stochastic_prev_effect, effect_for_compare, sizeof(*effect_for_compare)) != 0;
        if ((!r->stochastic_taa_enabled && cam_changed) || effect_changed) {
            renderer_reset_stochastic_accumulation(r);
            prev_cam_valid = false;
        }
        memcpy(&r->stochastic_prev_cam, cam, sizeof(*cam));
        memcpy(&r->stochastic_prev_effect, effect_for_compare, sizeof(*effect_for_compare));
        r->stochastic_prev_cam_valid = true;
        r->stochastic_prev_effect_valid = true;
        uint32_t samples_per_frame = r->stochastic_samples_per_frame;
        if (samples_per_frame < 1) samples_per_frame = 1;
        if (samples_per_frame > 16) samples_per_frame = 16;

        const bool use_taa = r->stochastic_taa_enabled;
        uint32_t render_samples = samples_per_frame;
        if (use_taa) {
            render_samples = r->stochastic_taa_current_samples;
            if (render_samples < 1) render_samples = 1;
            if (render_samples > 16) render_samples = 16;
        }
        float inv_view[16];
        if (use_taa) {
            if (!mat4_inverse(cam->view, inv_view)) {
                renderer_reset_stochastic_accumulation(r);
                memcpy(inv_view, cam->view, sizeof(inv_view));
                prev_cam_valid = false;
            }
        }

        uint32_t write_index = r->stochastic_accum_write_index & 1u;
        bool display_accum_texture = false;
        for (uint32_t sample_i = 0; sample_i < render_samples; ++sample_i) {
            r->stochastic_frame_seed++;
            float splat_jitter_px[2] = { 0.0f, 0.0f };
            if (use_taa) {
                uint32_t jitter_index = (r->stochastic_frame_seed % 1024u) + 1u;
                splat_jitter_px[0] = halton(jitter_index, 2u) - 0.5f;
                splat_jitter_px[1] = halton(jitter_index, 3u) - 0.5f;
            }

            sg_pass sample_pass = {};
            sample_pass.action.colors[0].load_action = SG_LOADACTION_CLEAR;
            sample_pass.action.colors[0].store_action = SG_STOREACTION_STORE;
            sample_pass.action.colors[0].clear_value = { 0.1f, 0.1f, 0.1f, 0.0f };
            sample_pass.action.depth.load_action = SG_LOADACTION_CLEAR;
            sample_pass.action.depth.store_action = use_taa ? SG_STOREACTION_STORE : SG_STOREACTION_DONTCARE;
            sample_pass.action.depth.clear_value = 1.0f;
            sample_pass.action.stencil.load_action = SG_LOADACTION_CLEAR;
            sample_pass.action.stencil.store_action = SG_STOREACTION_DONTCARE;
            sample_pass.action.stencil.clear_value = 0;
            sample_pass.attachments.colors[0] = r->stochastic_sample_color_view;
            sample_pass.attachments.depth_stencil = r->stochastic_depth_view;

            sg_begin_pass(&sample_pass);
            draw_world(r, scene, cam, overlay, nodes, splat_effect, SplatRenderMode::StochasticSplats, splat_jitter_px);
            sg_end_pass();

            StochasticSampleViews current_sample = {
                r->stochastic_sample_texture_view,
                r->stochastic_depth_texture_view,
            };

            if (use_taa && render_samples > 1) {
                uint32_t avg_write_index = sample_i & 1u;
                uint32_t avg_read_index = (avg_write_index + 1u) & 1u;

                sg_pass avg_pass = {};
                avg_pass.action.colors[0].load_action = (sample_i == 0) ? SG_LOADACTION_CLEAR : SG_LOADACTION_DONTCARE;
                avg_pass.action.colors[0].store_action = SG_STOREACTION_STORE;
                avg_pass.action.colors[0].clear_value = { 0.1f, 0.1f, 0.1f, 0.0f };
                avg_pass.attachments.colors[0] = r->stochastic_frame_avg_color_views[avg_write_index];
                sg_begin_pass(&avg_pass);
                sg_apply_pipeline(r->accum_pipeline);
                sg_bindings avg_bnd = {};
                avg_bnd.views[VIEW_sample_tex] = current_sample.color_texture;
                avg_bnd.samplers[SMP_sample_smp] = r->accum_sampler;
                avg_bnd.views[VIEW_history_tex] = (sample_i == 0)
                    ? current_sample.color_texture
                    : r->stochastic_frame_avg_texture_views[avg_read_index];
                avg_bnd.samplers[SMP_history_smp] = r->accum_sampler;
                sg_apply_bindings(&avg_bnd);
                AccumUBO_t avg_ubo = {};
                avg_ubo.sample_count = (float)(sample_i + 1u);
                sg_apply_uniforms(UB_AccumUBO, SG_RANGE_REF(avg_ubo));
                sg_draw(0, 3, 1);
                sg_end_pass();
            } else if (!use_taa && (r->stochastic_accumulation_enabled || render_samples > 1)) {
                uint32_t next_sample_count = r->stochastic_accumulation_enabled
                    ? r->stochastic_sample_count + 1
                    : sample_i + 1;
                write_index = r->stochastic_accumulation_enabled
                    ? (r->stochastic_accum_write_index & 1u)
                    : (sample_i & 1u);
                uint32_t read_index = (write_index + 1u) & 1u;

                sg_pass accum_pass = {};
                accum_pass.action.colors[0].load_action = (next_sample_count == 1) ? SG_LOADACTION_CLEAR : SG_LOADACTION_DONTCARE;
                accum_pass.action.colors[0].store_action = SG_STOREACTION_STORE;
                accum_pass.action.colors[0].clear_value = { 0.1f, 0.1f, 0.1f, 0.0f };
                accum_pass.attachments.colors[0] = r->stochastic_accum_color_views[write_index];
                sg_begin_pass(&accum_pass);
                sg_apply_pipeline(r->accum_pipeline);
                sg_bindings accum_bnd = {};
                accum_bnd.views[VIEW_sample_tex] = current_sample.color_texture;
                accum_bnd.samplers[SMP_sample_smp] = r->accum_sampler;
                accum_bnd.views[VIEW_history_tex] = (next_sample_count == 1)
                    ? current_sample.color_texture
                    : r->stochastic_accum_texture_views[read_index];
                accum_bnd.samplers[SMP_history_smp] = r->accum_sampler;
                sg_apply_bindings(&accum_bnd);
                AccumUBO_t accum_ubo = {};
                accum_ubo.sample_count = (float)next_sample_count;
                sg_apply_uniforms(UB_AccumUBO, SG_RANGE_REF(accum_ubo));
                sg_draw(0, 3, 1);
                sg_end_pass();

                display_accum_texture = true;
                if (r->stochastic_accumulation_enabled) {
                    r->stochastic_sample_count = next_sample_count;
                    r->stochastic_accum_write_index = (write_index + 1u) & 1u;
                }
            }
        }

        if (use_taa) {
            write_index = r->stochastic_accum_write_index & 1u;
            uint32_t read_index = (write_index + 1u) & 1u;
            sg_view current_taa_view = render_samples > 1
                ? r->stochastic_frame_avg_texture_views[(render_samples - 1u) & 1u]
                : r->stochastic_sample_texture_view;

            sg_pass taa_pass = {};
            taa_pass.action.colors[0].load_action = SG_LOADACTION_DONTCARE;
            taa_pass.action.colors[0].store_action = SG_STOREACTION_STORE;
            taa_pass.action.colors[1].load_action = SG_LOADACTION_DONTCARE;
            taa_pass.action.colors[1].store_action = SG_STOREACTION_STORE;
            taa_pass.attachments.colors[0] = r->stochastic_accum_color_views[write_index];
            taa_pass.attachments.colors[1] = r->stochastic_taa_xyz_color_views[write_index];
            sg_begin_pass(&taa_pass);
            sg_apply_pipeline(r->taa_accum_pipeline);
            StochasticSampleViews current_sample = {
                current_taa_view,
                r->stochastic_depth_texture_view,
            };
            sg_bindings taa_bnd = {};
            taa_bnd.views[VIEW_current_color_tex] = current_sample.color_texture;
            taa_bnd.samplers[SMP_current_color_smp] = r->accum_sampler;
            taa_bnd.views[VIEW_current_depth_tex] = current_sample.depth_texture;
            taa_bnd.samplers[SMP_current_depth_smp] = r->accum_sampler;
            taa_bnd.views[VIEW_history_color_tex] = r->stochastic_accum_texture_views[read_index];
            taa_bnd.samplers[SMP_history_color_smp] = r->accum_sampler;
            taa_bnd.views[VIEW_history_xyz_tex] = r->stochastic_taa_xyz_texture_views[read_index];
            taa_bnd.samplers[SMP_history_xyz_smp] = r->accum_sampler;
            sg_apply_bindings(&taa_bnd);

            TaaAccumUBO_t taa_ubo = {};
            bool has_history = r->stochastic_taa_prev_view_proj_valid && prev_cam_valid;
            memcpy(taa_ubo.inv_view, inv_view, sizeof(taa_ubo.inv_view));
            memcpy(taa_ubo.prev_view, has_history ? prev_cam.view : cam->view, sizeof(taa_ubo.prev_view));
            taa_ubo.viewport_orthographic[0] = cam->viewport[0];
            taa_ubo.viewport_orthographic[1] = cam->viewport[1];
            taa_ubo.viewport_orthographic[2] = cam->orthographic;
            taa_ubo.viewport_orthographic[3] = has_history ? prev_cam.orthographic : cam->orthographic;
            taa_ubo.focal_clip[0] = cam->persp_focal;
            taa_ubo.focal_clip[1] = cam->ortho_focal;
            taa_ubo.focal_clip[2] = cam->clip_y_sign;
            taa_ubo.focal_clip[3] = cam->clip_z_01;
            taa_ubo.prev_focal_clip[0] = has_history ? prev_cam.persp_focal : cam->persp_focal;
            taa_ubo.prev_focal_clip[1] = has_history ? prev_cam.ortho_focal : cam->ortho_focal;
            taa_ubo.prev_focal_clip[2] = has_history ? prev_cam.clip_y_sign : cam->clip_y_sign;
            taa_ubo.proj_z[0] = cam->proj[10];
            taa_ubo.proj_z[1] = cam->proj[14];
            taa_ubo.history_valid = has_history ? 1.0f : 0.0f;
            taa_ubo.view_changed = cam_changed ? 1.0f : 0.0f;
            sg_apply_uniforms(UB_TaaAccumUBO, SG_RANGE_REF(taa_ubo));
            sg_draw(0, 3, 1);
            sg_end_pass();

            memcpy(r->stochastic_taa_prev_view_proj, cam->view, sizeof(r->stochastic_taa_prev_view_proj));
            r->stochastic_taa_prev_view_proj_valid = true;
            r->stochastic_sample_count++;
            r->stochastic_accum_write_index = (write_index + 1u) & 1u;
            display_accum_texture = true;
        }

        sg_pass pass = {};
        pass.action.colors[0].load_action = SG_LOADACTION_CLEAR;
        pass.action.colors[0].store_action = SG_STOREACTION_STORE;
        pass.action.colors[0].clear_value = { 0.1f, 0.1f, 0.1f, 0.0f };
        pass.action.depth.load_action = SG_LOADACTION_CLEAR;
        pass.action.depth.store_action = SG_STOREACTION_DONTCARE;
        pass.action.depth.clear_value = 1.0f;
        pass.action.stencil.load_action = SG_LOADACTION_CLEAR;
        pass.action.stencil.store_action = SG_STOREACTION_DONTCARE;
        pass.action.stencil.clear_value = 0;
        pass.swapchain = sglue_swapchain();

        sg_begin_pass(&pass);
        sg_apply_pipeline(r->blit_pipeline);
        sg_bindings blit_bnd = {};
        blit_bnd.views[VIEW_display_tex] = display_accum_texture
            ? r->stochastic_accum_texture_views[write_index]
            : r->stochastic_sample_texture_view;
        blit_bnd.samplers[SMP_display_smp] = r->accum_sampler;
        sg_apply_bindings(&blit_bnd);
        sg_draw(0, 3, 1);
        PROFILE("render imgui pass") {
        PROFILE_GPU("imgui pass") {
        simgui_render();
        }
        }
        sg_end_pass();
        PROFILE("render commit") {
        sg_commit();
        PROFILE_GPU_COLLECT();
        }
        return;
    }

    sg_pass pass = {};
    pass.action.colors[0].load_action = SG_LOADACTION_CLEAR;
    pass.action.colors[0].store_action = SG_STOREACTION_STORE;
    pass.action.colors[0].clear_value = { 0.1f, 0.1f, 0.1f, 0.0f };
    pass.action.depth.load_action = SG_LOADACTION_CLEAR;
    pass.action.depth.store_action = SG_STOREACTION_DONTCARE;
    pass.action.depth.clear_value = 1.0f;
    pass.action.stencil.load_action = SG_LOADACTION_CLEAR;
    pass.action.stencil.store_action = SG_STOREACTION_DONTCARE;
    pass.action.stencil.clear_value = 0;
    // Backend-managed default surface (GL framebuffer 0 or current WebGPU canvas texture).
    pass.swapchain = sglue_swapchain();

    sg_begin_pass(&pass);
    draw_world(r, scene, cam, overlay, nodes, splat_effect, SplatRenderMode::AlphaBlendSorted);
    PROFILE("render imgui pass") {
    PROFILE_GPU("imgui pass") {
    simgui_render(); // imgui draws on top of the world inside the same pass
    }
    }
    sg_end_pass();
    PROFILE("render commit") {
    sg_commit();
    PROFILE_GPU_COLLECT();
    }
}

void renderer_destroy(Renderer* r) {
    renderer_destroy_shader_pipelines(r);
    if (r->overlay_sampler.id)    sg_destroy_sampler(r->overlay_sampler);
    if (r->mesh_sampler.id)       sg_destroy_sampler(r->mesh_sampler);
    if (r->accum_sampler.id)      sg_destroy_sampler(r->accum_sampler);
    if (r->gaussian_buffer_view.id) sg_destroy_view(r->gaussian_buffer_view);
    if (r->gaussian_buffer.id)    sg_destroy_buffer(r->gaussian_buffer);
    if (r->depth_key_buffer_view.id) sg_destroy_view(r->depth_key_buffer_view);
    if (r->depth_key_buffer.id)    sg_destroy_buffer(r->depth_key_buffer);
    if (r->sort_temp_key_buffer_view.id) sg_destroy_view(r->sort_temp_key_buffer_view);
    if (r->sort_temp_key_buffer.id) sg_destroy_buffer(r->sort_temp_key_buffer);
    if (r->sort_temp_index_buffer_view.id) sg_destroy_view(r->sort_temp_index_buffer_view);
    if (r->sort_temp_index_buffer.id) sg_destroy_buffer(r->sort_temp_index_buffer);
    if (r->sort_histogram_buffer_view.id) sg_destroy_view(r->sort_histogram_buffer_view);
    if (r->sort_histogram_buffer.id) sg_destroy_buffer(r->sort_histogram_buffer);
    if (r->projected_splat_buffer_view.id) sg_destroy_view(r->projected_splat_buffer_view);
    if (r->projected_splat_buffer.id) sg_destroy_buffer(r->projected_splat_buffer);
    if (r->visible_count_buffer_view.id) sg_destroy_view(r->visible_count_buffer_view);
    if (r->visible_count_buffer.id) sg_destroy_buffer(r->visible_count_buffer);
    if (r->splat_diagnostics_buffer_view.id) sg_destroy_view(r->splat_diagnostics_buffer_view);
    if (r->splat_diagnostics_buffer.id) sg_destroy_buffer(r->splat_diagnostics_buffer);
    renderer_destroy_stochastic_targets(r);
    gps_gpu_release(&r->gps_gpu);
    if (r->cube_vertex_buffer.id) sg_destroy_buffer(r->cube_vertex_buffer);
    if (r->cube_index_buffer.id)  sg_destroy_buffer(r->cube_index_buffer);
    if (r->unsorted_index_buffer_view.id) sg_destroy_view(r->unsorted_index_buffer_view);
    if (r->unsorted_index_buffer.id) sg_destroy_buffer(r->unsorted_index_buffer);
    mesh_gpu_release(&r->mesh_gpu);
    mesh_gpu_release(&r->object_gpu);
}
