#include "renderer.h"
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <cmath>
#include "sokol_gfx.h"
#define SOKOL_IMGUI_NO_SOKOL_APP
#include "imgui.h"
#include "sokol_imgui.h"
#include "profiler.h"

// Generated by sokol-shdc; included via third_party_impl.cpp's translation
// unit for the impls, and here for the {prog}_shader_desc() helpers and the
// SLOT_*, UB_*, VIEW_*, SMP_*, and UB struct definitions.
#include "../shaders/wireframe.glsl.h"
#include "../shaders/overlay.glsl.h"
#include "../shaders/darken.glsl.h"
#include "../shaders/mesh.glsl.h"
#include "../shaders/splat.glsl.h"

// Forward decl (defined later in this TU).
static void mesh_gpu_release(MeshGpu* m);

bool renderer_init(Renderer* r, SDL_Window* window) {
    memset(r, 0, sizeof(*r));
    r->window = window;
    r->mesh_transform.scale = 1.0f;
    r->object_transform.scale = 1.0f;
    PROFILE_GPU_CONTEXT();

    // --- Splat pipeline -------------------------------------------------
    {
        sg_pipeline_desc pd = {};
        pd.shader = sg_make_shader(splat_shader_desc(sg_query_backend()));
        pd.primitive_type = SG_PRIMITIVETYPE_TRIANGLES;
        // Per-instance attribute (uint splat_id) on buffer slot 0.
        pd.layout.buffers[0].stride = sizeof(uint32_t);
        pd.layout.buffers[0].step_func = SG_VERTEXSTEP_PER_INSTANCE;
        pd.layout.attrs[ATTR_splat_splat_id].buffer_index = 0;
        pd.layout.attrs[ATTR_splat_splat_id].offset = 0;
        pd.layout.attrs[ATTR_splat_splat_id].format = SG_VERTEXFORMAT_UINT;
        // Splats only test depth (so they don't poke through the mesh from
        // behind), they don't write depth or stencil.
        pd.depth.compare = SG_COMPAREFUNC_LESS;
        pd.depth.write_enabled = false;
        pd.depth.pixel_format = SG_PIXELFORMAT_DEPTH_STENCIL;
        pd.cull_mode = SG_CULLMODE_NONE;
        pd.colors[0].pixel_format = SG_PIXELFORMAT_RGBA8;
        pd.colors[0].blend.enabled = true;
        pd.colors[0].blend.src_factor_rgb = SG_BLENDFACTOR_ONE;
        pd.colors[0].blend.dst_factor_rgb = SG_BLENDFACTOR_ONE_MINUS_SRC_ALPHA;
        pd.colors[0].blend.op_rgb = SG_BLENDOP_ADD;
        // Alpha factor preserves the previous behavior where the alpha
        // channel was scaled by a "blend constant" to control occlusion of
        // the wireframe pass. sokol_gfx has no equivalent of
        // SDL_SetGPUBlendConstants, so this stage now uses ONE/ONE-MINUS
        // for alpha — wireframe_occlusion is therefore no longer honored.
        pd.colors[0].blend.src_factor_alpha = SG_BLENDFACTOR_ONE;
        pd.colors[0].blend.dst_factor_alpha = SG_BLENDFACTOR_ONE_MINUS_SRC_ALPHA;
        pd.colors[0].blend.op_alpha = SG_BLENDOP_ADD;
        pd.colors[0].write_mask = SG_COLORMASK_RGBA;
        pd.label = "splat-pipeline";
        r->splat_pipeline = sg_make_pipeline(&pd);
    }

    // --- Overlay pipeline -----------------------------------------------
    {
        sg_pipeline_desc pd = {};
        pd.shader = sg_make_shader(overlay_shader_desc(sg_query_backend()));
        pd.primitive_type = SG_PRIMITIVETYPE_TRIANGLES;
        pd.cull_mode = SG_CULLMODE_NONE;
        pd.depth.pixel_format = SG_PIXELFORMAT_DEPTH_STENCIL;
        // Stencil: only draw where stencil != 1 (i.e. NOT inside the mesh
        // silhouette). Inside the mesh region, the mesh + splat composite
        // stays. ref value baked into the pipeline.
        pd.stencil.enabled = true;
        pd.stencil.read_mask = 0xFF;
        pd.stencil.write_mask = 0x00;
        pd.stencil.ref = 1;
        pd.stencil.front.compare = SG_COMPAREFUNC_NOT_EQUAL;
        pd.stencil.front.fail_op = SG_STENCILOP_KEEP;
        pd.stencil.front.depth_fail_op = SG_STENCILOP_KEEP;
        pd.stencil.front.pass_op = SG_STENCILOP_KEEP;
        pd.stencil.back = pd.stencil.front;
        pd.colors[0].pixel_format = SG_PIXELFORMAT_RGBA8;
        pd.colors[0].blend.enabled = true;
        pd.colors[0].blend.src_factor_rgb = SG_BLENDFACTOR_ONE;
        pd.colors[0].blend.dst_factor_rgb = SG_BLENDFACTOR_ONE_MINUS_SRC_ALPHA;
        pd.colors[0].blend.op_rgb = SG_BLENDOP_ADD;
        pd.colors[0].blend.src_factor_alpha = SG_BLENDFACTOR_ONE;
        pd.colors[0].blend.dst_factor_alpha = SG_BLENDFACTOR_ONE_MINUS_SRC_ALPHA;
        pd.colors[0].blend.op_alpha = SG_BLENDOP_ADD;
        pd.colors[0].write_mask = (sg_color_mask)(SG_COLORMASK_R | SG_COLORMASK_G | SG_COLORMASK_B);
        pd.label = "overlay-pipeline";
        r->overlay_pipeline = sg_make_pipeline(&pd);
    }

    // --- Darken pipeline ------------------------------------------------
    // Fullscreen translucent black quad used to dim the FPS view behind the
    // top-down map overlay. Built even though the map_cam two-pass path is
    // disabled in this commit, so the pipeline is ready when it's restored.
    {
        sg_pipeline_desc pd = {};
        pd.shader = sg_make_shader(darken_shader_desc(sg_query_backend()));
        pd.primitive_type = SG_PRIMITIVETYPE_TRIANGLES;
        pd.cull_mode = SG_CULLMODE_NONE;
        pd.depth.pixel_format = SG_PIXELFORMAT_DEPTH_STENCIL;
        // No depth/stencil testing.
        pd.colors[0].pixel_format = SG_PIXELFORMAT_RGBA8;
        pd.colors[0].blend.enabled = true;
        pd.colors[0].blend.src_factor_rgb = SG_BLENDFACTOR_ONE;
        pd.colors[0].blend.dst_factor_rgb = SG_BLENDFACTOR_ONE_MINUS_SRC_ALPHA;
        pd.colors[0].blend.op_rgb = SG_BLENDOP_ADD;
        pd.colors[0].blend.src_factor_alpha = SG_BLENDFACTOR_ONE;
        pd.colors[0].blend.dst_factor_alpha = SG_BLENDFACTOR_ONE_MINUS_SRC_ALPHA;
        pd.colors[0].blend.op_alpha = SG_BLENDOP_ADD;
        pd.colors[0].write_mask = (sg_color_mask)(SG_COLORMASK_R | SG_COLORMASK_G | SG_COLORMASK_B);
        pd.label = "darken-pipeline";
        r->darken_pipeline = sg_make_pipeline(&pd);
    }

    // --- Wireframe pipeline ---------------------------------------------
    {
        sg_pipeline_desc pd = {};
        pd.shader = sg_make_shader(wireframe_shader_desc(sg_query_backend()));
        pd.primitive_type = SG_PRIMITIVETYPE_LINES;
        pd.index_type = SG_INDEXTYPE_UINT16;
        pd.cull_mode = SG_CULLMODE_NONE;
        pd.layout.buffers[0].stride = 3 * sizeof(float);
        pd.layout.buffers[0].step_func = SG_VERTEXSTEP_PER_VERTEX;
        pd.layout.attrs[ATTR_wireframe_in_position].buffer_index = 0;
        pd.layout.attrs[ATTR_wireframe_in_position].offset = 0;
        pd.layout.attrs[ATTR_wireframe_in_position].format = SG_VERTEXFORMAT_FLOAT3;
        pd.depth.pixel_format = SG_PIXELFORMAT_DEPTH_STENCIL;
        pd.colors[0].pixel_format = SG_PIXELFORMAT_RGBA8;
        pd.colors[0].blend.enabled = true;
        pd.colors[0].blend.src_factor_rgb = SG_BLENDFACTOR_ONE_MINUS_DST_ALPHA;
        pd.colors[0].blend.dst_factor_rgb = SG_BLENDFACTOR_ONE;
        pd.colors[0].blend.op_rgb = SG_BLENDOP_ADD;
        pd.colors[0].blend.src_factor_alpha = SG_BLENDFACTOR_ZERO;
        pd.colors[0].blend.dst_factor_alpha = SG_BLENDFACTOR_ONE;
        pd.colors[0].blend.op_alpha = SG_BLENDOP_ADD;
        pd.colors[0].write_mask = (sg_color_mask)(SG_COLORMASK_R | SG_COLORMASK_G | SG_COLORMASK_B);
        pd.label = "wireframe-pipeline";
        r->wireframe_pipeline = sg_make_pipeline(&pd);
    }

    // --- Mesh pipeline --------------------------------------------------
    {
        sg_pipeline_desc pd = {};
        pd.shader = sg_make_shader(mesh_shader_desc(sg_query_backend()));
        pd.primitive_type = SG_PRIMITIVETYPE_TRIANGLES;
        pd.index_type = SG_INDEXTYPE_UINT32;
        pd.cull_mode = SG_CULLMODE_BACK;
        pd.face_winding = SG_FACEWINDING_CW;
        pd.layout.buffers[0].stride = 5 * sizeof(float);   // vec3 pos + vec2 uv
        pd.layout.buffers[0].step_func = SG_VERTEXSTEP_PER_VERTEX;
        pd.layout.attrs[ATTR_mesh_in_position].buffer_index = 0;
        pd.layout.attrs[ATTR_mesh_in_position].offset = 0;
        pd.layout.attrs[ATTR_mesh_in_position].format = SG_VERTEXFORMAT_FLOAT3;
        pd.layout.attrs[ATTR_mesh_in_uv].buffer_index = 0;
        pd.layout.attrs[ATTR_mesh_in_uv].offset = 3 * sizeof(float);
        pd.layout.attrs[ATTR_mesh_in_uv].format = SG_VERTEXFORMAT_FLOAT2;
        pd.depth.compare = SG_COMPAREFUNC_LESS;
        pd.depth.write_enabled = true;
        pd.depth.pixel_format = SG_PIXELFORMAT_DEPTH_STENCIL;
        // Every mesh pixel writes 1 to stencil, marking the mesh region.
        // The overlay pass draws only where stencil != 1.
        pd.stencil.enabled = true;
        pd.stencil.read_mask = 0xFF;
        pd.stencil.write_mask = 0xFF;
        pd.stencil.ref = 1;
        pd.stencil.front.compare = SG_COMPAREFUNC_ALWAYS;
        pd.stencil.front.fail_op = SG_STENCILOP_KEEP;
        pd.stencil.front.depth_fail_op = SG_STENCILOP_KEEP;
        pd.stencil.front.pass_op = SG_STENCILOP_REPLACE;
        pd.stencil.back = pd.stencil.front;
        pd.colors[0].pixel_format = SG_PIXELFORMAT_RGBA8;
        pd.colors[0].blend.enabled = false;
        pd.colors[0].write_mask = SG_COLORMASK_RGBA;
        pd.label = "mesh-pipeline";
        r->mesh_pipeline = sg_make_pipeline(&pd);
    }

    // --- Samplers -------------------------------------------------------
    {
        sg_sampler_desc sd = {};
        sd.min_filter = SG_FILTER_LINEAR;
        sd.mag_filter = SG_FILTER_LINEAR;
        sd.mipmap_filter = SG_FILTER_NEAREST;
        sd.wrap_u = SG_WRAP_REPEAT;
        sd.wrap_v = SG_WRAP_CLAMP_TO_EDGE;
        sd.wrap_w = SG_WRAP_CLAMP_TO_EDGE;
        sd.label = "overlay-sampler";
        r->overlay_sampler = sg_make_sampler(&sd);
    }
    {
        sg_sampler_desc sd = {};
        sd.min_filter = SG_FILTER_NEAREST;
        sd.mag_filter = SG_FILTER_NEAREST;
        sd.mipmap_filter = SG_FILTER_NEAREST;
        sd.wrap_u = SG_WRAP_REPEAT;
        sd.wrap_v = SG_WRAP_REPEAT;
        sd.wrap_w = SG_WRAP_REPEAT;
        sd.label = "mesh-sampler";
        r->mesh_sampler = sg_make_sampler(&sd);
    }
    {
        // Gaussian sampler. The splat shader uses texelFetch which ignores
        // filter/wrap state, but sokol_gfx still requires a sampler when
        // binding a sampled texture.
        sg_sampler_desc sd = {};
        sd.min_filter = SG_FILTER_NEAREST;
        sd.mag_filter = SG_FILTER_NEAREST;
        sd.mipmap_filter = SG_FILTER_NEAREST;
        sd.wrap_u = SG_WRAP_CLAMP_TO_EDGE;
        sd.wrap_v = SG_WRAP_CLAMP_TO_EDGE;
        sd.wrap_w = SG_WRAP_CLAMP_TO_EDGE;
        sd.label = "gaussian-sampler";
        r->gaussian_sampler = sg_make_sampler(&sd);
    }

    // --- Cube geometry (unit cube centered at origin, ±0.5) -------------
    static const float cube_verts[8 * 3] = {
        -0.5f, -0.5f, -0.5f,
         0.5f, -0.5f, -0.5f,
         0.5f,  0.5f, -0.5f,
        -0.5f,  0.5f, -0.5f,
        -0.5f, -0.5f,  0.5f,
         0.5f, -0.5f,  0.5f,
         0.5f,  0.5f,  0.5f,
        -0.5f,  0.5f,  0.5f,
    };
    static const uint16_t cube_indices[24] = {
        0,1, 1,2, 2,3, 3,0,
        4,5, 5,6, 6,7, 7,4,
        0,4, 1,5, 2,6, 3,7,
    };
    {
        sg_buffer_desc bd = {};
        bd.usage.vertex_buffer = true;
        bd.data = SG_RANGE(cube_verts);
        bd.label = "cube-vb";
        r->cube_vertex_buffer = sg_make_buffer(&bd);
    }
    {
        sg_buffer_desc bd = {};
        bd.usage.index_buffer = true;
        bd.data = SG_RANGE(cube_indices);
        bd.label = "cube-ib";
        r->cube_index_buffer = sg_make_buffer(&bd);
    }

    fprintf(stderr, "Renderer init OK\n");
    return true;
}

// Gaussian texture layout: each gaussian occupies 16 consecutive RGBA32F
// texels (= 64 floats, same byte layout as GpuGaussian). Width is fixed at
// 4096 (POT, so the shader can use bit ops). Height grows to hold N gaussians.
#define GAUSSIAN_TEX_WIDTH      4096u
#define GAUSSIAN_TEXELS_PER     16u
#define GAUSSIAN_BYTES_PER_TEXEL 16u  // RGBA32F

void renderer_upload_gaussians(Renderer* r, const GaussianScene* scene) {
    r->gaussian_count = scene->gaussian_count;

    uint32_t total_texels = scene->gaussian_count * GAUSSIAN_TEXELS_PER;
    uint32_t tex_w = GAUSSIAN_TEX_WIDTH;
    uint32_t tex_h = (total_texels + tex_w - 1u) / tex_w;
    r->gaussian_tex_w = tex_w;
    r->gaussian_tex_h = tex_h;

    // Pack into a tight buffer sized for the full tex_w*tex_h grid (trailing
    // slack zeroed for cleanliness).
    uint32_t tex_buf_size = tex_w * tex_h * GAUSSIAN_BYTES_PER_TEXEL;
    uint32_t payload_size = scene->gaussian_count * (uint32_t)sizeof(GpuGaussian);
    uint8_t* tex_data = (uint8_t*)malloc(tex_buf_size);
    GpuGaussian* gpu_data = pack_gpu_gaussians(scene);
    memcpy(tex_data, gpu_data, payload_size);
    if (tex_buf_size > payload_size) {
        memset(tex_data + payload_size, 0, tex_buf_size - payload_size);
    }
    free(gpu_data);

    sg_image_desc id = {};
    id.type = SG_IMAGETYPE_2D;
    id.width = (int)tex_w;
    id.height = (int)tex_h;
    id.num_slices = 1;
    id.num_mipmaps = 1;
    id.pixel_format = SG_PIXELFORMAT_RGBA32F;
    id.data.mip_levels[0].ptr = tex_data;
    id.data.mip_levels[0].size = tex_buf_size;
    id.label = "gaussian-tex";
    r->gaussian_texture = sg_make_image(&id);
    free(tex_data);

    sg_view_desc vd = {};
    vd.texture.image = r->gaussian_texture;
    vd.label = "gaussian-tex-view";
    r->gaussian_texture_view = sg_make_view(&vd);

    // Dynamic per-instance sorted-index buffer (one uint per gaussian).
    sg_buffer_desc bd = {};
    bd.usage.vertex_buffer = true;
    bd.usage.stream_update = true;
    bd.size = scene->gaussian_count * sizeof(uint32_t);
    bd.label = "splat-index-vb";
    r->index_buffer = sg_make_buffer(&bd);
    r->index_buffer_capacity = scene->gaussian_count;

    fprintf(stderr, "Uploaded %u gaussians (gaussian_tex = %ux%u RGBA32F)\n",
            scene->gaussian_count, tex_w, tex_h);
}

// Release everything held by a MeshGpu and zero it. Safe to call on an
// already-empty MeshGpu (all fields NULL/0).
static void mesh_gpu_release(MeshGpu* m) {
    if (m->vertex_buffer.id) sg_destroy_buffer(m->vertex_buffer);
    if (m->index_buffer.id)  sg_destroy_buffer(m->index_buffer);
    if (m->textures) {
        for (uint32_t i = 0; i < m->texture_count; ++i) {
            if (m->texture_views && m->texture_views[i].id) sg_destroy_view(m->texture_views[i]);
            if (m->textures[i].id) sg_destroy_image(m->textures[i]);
        }
        free(m->textures);
        free(m->texture_views);
    }
    if (m->default_texture_view.id) sg_destroy_view(m->default_texture_view);
    if (m->default_texture.id)      sg_destroy_image(m->default_texture);
    if (m->submeshes) free(m->submeshes);
    memset(m, 0, sizeof(*m));
}

// Upload mesh geometry, textures, and submesh metadata to `out`. Replaces any
// existing GPU resources in `out`. Returns true on success.
static bool mesh_gpu_upload(const Mesh* mesh, MeshGpu* out) {
    mesh_gpu_release(out);

    uint32_t vert_count  = mesh->vertex_count;
    uint32_t index_count = mesh->index_count;
    uint32_t vb_size = vert_count * 5 * sizeof(float); // vec3 pos + vec2 uv
    uint32_t ib_size = index_count * sizeof(uint32_t);

    {
        sg_buffer_desc bd = {};
        bd.usage.vertex_buffer = true;
        bd.data.ptr = mesh->vertices;
        bd.data.size = vb_size;
        bd.label = "mesh-vb";
        out->vertex_buffer = sg_make_buffer(&bd);
    }
    {
        sg_buffer_desc bd = {};
        bd.usage.index_buffer = true;
        bd.data.ptr = mesh->indices;
        bd.data.size = ib_size;
        bd.label = "mesh-ib";
        out->index_buffer = sg_make_buffer(&bd);
    }

    // Default 1x1 white texture (fallback for submeshes without a material).
    {
        static const uint8_t white_px[4] = { 255, 255, 255, 255 };
        sg_image_desc id = {};
        id.type = SG_IMAGETYPE_2D;
        id.width = 1;
        id.height = 1;
        id.num_slices = 1;
        id.num_mipmaps = 1;
        id.pixel_format = SG_PIXELFORMAT_RGBA8;
        id.data.mip_levels[0].ptr = white_px;
        id.data.mip_levels[0].size = sizeof(white_px);
        id.label = "mesh-default-tex";
        out->default_texture = sg_make_image(&id);

        sg_view_desc vd = {};
        vd.texture.image = out->default_texture;
        vd.label = "mesh-default-tex-view";
        out->default_texture_view = sg_make_view(&vd);
    }

    // Per-material textures.
    if (mesh->texture_count > 0) {
        out->textures = (sg_image*)calloc(mesh->texture_count, sizeof(sg_image));
        out->texture_views = (sg_view*)calloc(mesh->texture_count, sizeof(sg_view));
        out->texture_count = mesh->texture_count;
        for (uint32_t i = 0; i < mesh->texture_count; ++i) {
            const MeshTexture& mt = mesh->textures[i];
            sg_image_desc id = {};
            id.type = SG_IMAGETYPE_2D;
            id.width = mt.w;
            id.height = mt.h;
            id.num_slices = 1;
            id.num_mipmaps = 1;
            id.pixel_format = SG_PIXELFORMAT_RGBA8;
            id.data.mip_levels[0].ptr = mt.rgba;
            id.data.mip_levels[0].size = (size_t)mt.w * (size_t)mt.h * 4u;
            id.label = "mesh-tex";
            out->textures[i] = sg_make_image(&id);

            sg_view_desc vd = {};
            vd.texture.image = out->textures[i];
            vd.label = "mesh-tex-view";
            out->texture_views[i] = sg_make_view(&vd);
        }
    }

    // Copy submesh metadata.
    out->submesh_count = mesh->submesh_count;
    if (mesh->submesh_count > 0) {
        out->submeshes = (MeshSubmesh*)malloc(mesh->submesh_count * sizeof(MeshSubmesh));
        memcpy(out->submeshes, mesh->submeshes, mesh->submesh_count * sizeof(MeshSubmesh));
    }

    fprintf(stderr, "Uploaded mesh: %u verts, %u indices, %u textures, %u submeshes\n",
            vert_count, index_count, mesh->texture_count, mesh->submesh_count);

    return true;
}

bool renderer_upload_mesh(Renderer* r, const Mesh* mesh) {
    return mesh_gpu_upload(mesh, &r->mesh_gpu);
}

bool renderer_upload_object_mesh(Renderer* r, const Mesh* mesh) {
    return mesh_gpu_upload(mesh, &r->object_gpu);
}

// Multiply two column-major 4x4 matrices: out = a * b
static void mat4_mul(const float* a, const float* b, float* out) {
    for (int c = 0; c < 4; c++) {
        for (int r = 0; r < 4; r++) {
            out[c*4+r] = a[0*4+r]*b[c*4+0] + a[1*4+r]*b[c*4+1] + a[2*4+r]*b[c*4+2] + a[3*4+r]*b[c*4+3];
        }
    }
}

// Build a column-major translation+scale model matrix.
static void mat4_translate_scale(float tx, float ty, float tz, float s, float* out) {
    memset(out, 0, 16 * sizeof(float));
    out[0]  = s;
    out[5]  = s;
    out[10] = s;
    out[12] = tx;
    out[13] = ty;
    out[14] = tz;
    out[15] = 1.0f;
}

// Build column-major model matrix: T * Rz * Ry * Rx * S (intrinsic Z-Y-X Euler).
static void mat4_from_transform(const MeshTransform& t, float* out) {
    float cx = cosf(t.rotation_euler[0]), sx = sinf(t.rotation_euler[0]);
    float cy = cosf(t.rotation_euler[1]), sy = sinf(t.rotation_euler[1]);
    float cz = cosf(t.rotation_euler[2]), sz = sinf(t.rotation_euler[2]);
    float s = t.scale;

    float r00 = cy * cz;
    float r01 = sx * sy * cz - cx * sz;
    float r02 = cx * sy * cz + sx * sz;
    float r10 = cy * sz;
    float r11 = sx * sy * sz + cx * cz;
    float r12 = cx * sy * sz - sx * cz;
    float r20 = -sy;
    float r21 = sx * cy;
    float r22 = cx * cy;

    out[0]  = r00 * s; out[1]  = r10 * s; out[2]  = r20 * s; out[3]  = 0.0f;
    out[4]  = r01 * s; out[5]  = r11 * s; out[6]  = r21 * s; out[7]  = 0.0f;
    out[8]  = r02 * s; out[9]  = r12 * s; out[10] = r22 * s; out[11] = 0.0f;
    out[12] = t.translation[0];
    out[13] = t.translation[1];
    out[14] = t.translation[2];
    out[15] = 1.0f;
}

// Draws mesh + splats + (optional) panorama overlay + (optional) wireframe
// nodes for one camera into the currently-active sg_begin_pass. ImGui is NOT
// drawn here; the caller is responsible for that after this returns.
static void draw_world(Renderer* r, const GaussianScene* scene, const CameraUniforms* cam,
                       const OverlayParams* overlay, const NodeRenderParams* nodes) {
    // VP shared by both mesh slots and the wireframe pass.
    float vp[16];
    mat4_mul(cam->proj, cam->view, vp);

    // Mesh: writes color, depth, and stencil=1 to mark its silhouette. Same
    // lambda is reused for the static --object mesh (with its own MVP).
    auto draw_mesh_slot = [&](const MeshGpu* m, const float* mvp) {
        if (m->vertex_buffer.id == 0 || m->index_buffer.id == 0 || m->submesh_count == 0) return;

        sg_apply_pipeline(r->mesh_pipeline);

        for (uint32_t i = 0; i < m->submesh_count; ++i) {
            const MeshSubmesh& sm = m->submeshes[i];
            if (sm.index_count == 0) continue;

            sg_view tex_view = m->default_texture_view;
            float use_texture = 0.0f;
            if (sm.texture_id >= 0 && (uint32_t)sm.texture_id < m->texture_count
                && m->textures[sm.texture_id].id) {
                tex_view = m->texture_views[sm.texture_id];
                use_texture = 1.0f;
            }

            sg_bindings bnd = {};
            bnd.vertex_buffers[0] = m->vertex_buffer;
            bnd.index_buffer = m->index_buffer;
            bnd.views[VIEW_mesh_tex] = tex_view;
            bnd.samplers[SMP_mesh_smp] = r->mesh_sampler;
            sg_apply_bindings(&bnd);

            MeshUniforms_t u = {};
            memcpy(u.mvp, mvp, sizeof(u.mvp));
            u.color[0] = u.color[1] = u.color[2] = u.color[3] = 1.0f;
            u.use_texture = use_texture;
            sg_apply_uniforms(UB_MeshUniforms, SG_RANGE_REF(u));

            sg_draw((int)sm.index_offset, (int)sm.index_count, 1);
        }
    };

    PROFILE("render mesh pass") {
    PROFILE_GPU("mesh pass") {
    // Primary animated mesh.
    {
        float model[16];
        mat4_from_transform(r->mesh_transform, model);
        float mvp[16];
        mat4_mul(vp, model, mvp);
        draw_mesh_slot(&r->mesh_gpu, mvp);
    }

    // Static --object mesh (transformed by object_transform; identity by default).
    if (r->object_gpu.vertex_buffer.id) {
        float obj_model[16];
        mat4_from_transform(r->object_transform, obj_model);
        float obj_mvp[16];
        mat4_mul(vp, obj_model, obj_mvp);
        draw_mesh_slot(&r->object_gpu, obj_mvp);
    }
    }
    }

    // Splats
    if (scene->visible_count > 0 && r->gaussian_texture.id && r->index_buffer.id) {
        PROFILE("render splat pass") {
        PROFILE_GPU("splat pass") {
        sg_apply_pipeline(r->splat_pipeline);

        sg_bindings bnd = {};
        bnd.vertex_buffers[0] = r->index_buffer;            // per-instance sorted ids
        bnd.views[VIEW_gaussian_tex] = r->gaussian_texture_view;
        bnd.samplers[SMP_gaussian_smp] = r->gaussian_sampler;
        sg_apply_bindings(&bnd);

        // The CameraUniforms host struct lays out 1:1 with the generated
        // CameraUBO_t (verified by the existing usage in main.cpp).
        sg_apply_uniforms(UB_CameraUBO, sg_range{ cam, sizeof(CameraUniforms) });

        // 6 vertices per quad, scene->visible_count instances.
        sg_draw(0, 6, (int)scene->visible_count);
        }
        }
    }

    // Equirectangular panorama overlay.
    if (overlay && overlay->texture.id && overlay->alpha > 0.0f) {
        PROFILE("render overlay pass") {
        PROFILE_GPU("overlay pass") {
        sg_apply_pipeline(r->overlay_pipeline);

        sg_bindings bnd = {};
        bnd.views[VIEW_panorama_tex] = overlay->texture_view;
        bnd.samplers[SMP_panorama_smp] = r->overlay_sampler;
        sg_apply_bindings(&bnd);

        OverlayUniforms_t u = {};
        memcpy(u.camera_ray_basis, overlay->camera_ray_basis, sizeof(u.camera_ray_basis));
        memcpy(u.camera_tan_half_fov, overlay->camera_tan_half_fov, sizeof(u.camera_tan_half_fov));
        memcpy(u.ref_rotation, overlay->ref_rotation, sizeof(u.ref_rotation));
        u.alpha = overlay->alpha;
        sg_apply_uniforms(UB_OverlayUniforms, SG_RANGE_REF(u));

        sg_draw(0, 3, 1); // fullscreen triangle
        }
        }
    }

    // Wireframe node cubes.
    if (nodes && nodes->count > 0) {
        PROFILE("render wireframe pass") {
        PROFILE_GPU("wireframe pass") {
        sg_apply_pipeline(r->wireframe_pipeline);

        float scale = nodes->half_size * 2.0f;
        for (uint32_t i = 0; i < nodes->count; i++) {
            const float* p = &nodes->positions[i * 3];

            sg_bindings bnd = {};
            bnd.vertex_buffers[0] = r->cube_vertex_buffer;
            bnd.index_buffer = r->cube_index_buffer;
            sg_apply_bindings(&bnd);

            float model[16];
            mat4_translate_scale(p[0], p[1], p[2], scale, model);
            float mvp[16];
            mat4_mul(vp, model, mvp);

            WireframeUniforms_t u = {};
            memcpy(u.mvp, mvp, sizeof(u.mvp));
            u.color[0] = 0.0f; u.color[1] = 1.0f; u.color[2] = 1.0f; u.color[3] = 1.0f;
            sg_apply_uniforms(UB_WireframeUniforms, SG_RANGE_REF(u));

            sg_draw(0, 24, 1);
        }
        }
        }
    }
}

void renderer_draw_frame(Renderer* r, GaussianScene* scene, const CameraUniforms* cam,
                         const OverlayParams* overlay, const NodeRenderParams* nodes,
                         float wireframe_occlusion, const CameraUniforms* map_cam) {
    (void)wireframe_occlusion; // see splat-pipeline blend comment in renderer_init
    (void)map_cam;             // TODO: restore the two-pass top-down map overlay in a later commit

    // Push fresh sorted indices to the GPU once per frame.
    if (scene->visible_count > 0 && r->index_buffer.id) {
        PROFILE("update sorted index buffer") {
        sg_range range;
        range.ptr = scene->sorted_indices;
        range.size = scene->visible_count * sizeof(uint32_t);
        sg_update_buffer(r->index_buffer, &range);
        }
    }

    int win_w = 0, win_h = 0;
    SDL_GetWindowSize(r->window, &win_w, &win_h);

    sg_pass pass = {};
    pass.action.colors[0].load_action = SG_LOADACTION_CLEAR;
    pass.action.colors[0].store_action = SG_STOREACTION_STORE;
    pass.action.colors[0].clear_value = { 0.1f, 0.1f, 0.1f, 0.0f };
    pass.action.depth.load_action = SG_LOADACTION_CLEAR;
    pass.action.depth.store_action = SG_STOREACTION_DONTCARE;
    pass.action.depth.clear_value = 1.0f;
    pass.action.stencil.load_action = SG_LOADACTION_CLEAR;
    pass.action.stencil.store_action = SG_STOREACTION_DONTCARE;
    pass.action.stencil.clear_value = 0;
    // SDL3-managed GL context: framebuffer 0 is the default backbuffer.
    pass.swapchain.width = win_w;
    pass.swapchain.height = win_h;
    pass.swapchain.sample_count = 1;
    pass.swapchain.color_format = SG_PIXELFORMAT_RGBA8;
    pass.swapchain.depth_format = SG_PIXELFORMAT_DEPTH_STENCIL;
    pass.swapchain.gl.framebuffer = 0;

    sg_begin_pass(&pass);
    draw_world(r, scene, cam, overlay, nodes);
    PROFILE("render imgui pass") {
    PROFILE_GPU("imgui pass") {
    simgui_render(); // imgui draws on top of the world inside the same pass
    }
    }
    sg_end_pass();
    PROFILE("render commit") {
    sg_commit();
    PROFILE_GPU_COLLECT();
    SDL_GL_SwapWindow(r->window);
    }
}

void renderer_destroy(Renderer* r) {
    if (r->splat_pipeline.id)     sg_destroy_pipeline(r->splat_pipeline);
    if (r->overlay_pipeline.id)   sg_destroy_pipeline(r->overlay_pipeline);
    if (r->darken_pipeline.id)    sg_destroy_pipeline(r->darken_pipeline);
    if (r->wireframe_pipeline.id) sg_destroy_pipeline(r->wireframe_pipeline);
    if (r->mesh_pipeline.id)      sg_destroy_pipeline(r->mesh_pipeline);
    if (r->overlay_sampler.id)    sg_destroy_sampler(r->overlay_sampler);
    if (r->mesh_sampler.id)       sg_destroy_sampler(r->mesh_sampler);
    if (r->gaussian_sampler.id)   sg_destroy_sampler(r->gaussian_sampler);
    if (r->gaussian_texture_view.id) sg_destroy_view(r->gaussian_texture_view);
    if (r->gaussian_texture.id)   sg_destroy_image(r->gaussian_texture);
    if (r->cube_vertex_buffer.id) sg_destroy_buffer(r->cube_vertex_buffer);
    if (r->cube_index_buffer.id)  sg_destroy_buffer(r->cube_index_buffer);
    if (r->index_buffer.id)       sg_destroy_buffer(r->index_buffer);
    mesh_gpu_release(&r->mesh_gpu);
    mesh_gpu_release(&r->object_gpu);
}
