#include "renderer.h"
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <cmath>
#include <cstdint>
#if defined(__EMSCRIPTEN__) && defined(SOKOL_WGPU)
#include <utility>
#include <webgpu/webgpu_cpp.h>
#endif
#include "sokol_gfx.h"
#define SOKOL_IMGUI_NO_SOKOL_APP
#include "imgui.h"
#include "sokol_imgui.h"
#include "profiler.h"
#include "maths.h"

// Generated by sokol-shdc; included via third_party_impl.cpp's translation
// unit for the impls, and here for the {prog}_shader_desc() helpers and the
// SLOT_*, UB_*, VIEW_*, SMP_*, and UB struct definitions.
#include "../shaders/wireframe.glsl.h"
#include "../shaders/overlay.glsl.h"
#include "../shaders/darken.glsl.h"
#include "../shaders/mesh.glsl.h"
#include "../shaders/splat.glsl.h"
#include "../shaders/accum.glsl.h"

// Forward decl (defined later in this TU).
static void mesh_gpu_release(MeshGpu* m);

sg_pixel_format renderer_default_color_format(void) {
#if defined(__EMSCRIPTEN__) && defined(SOKOL_WGPU)
    return SG_PIXELFORMAT_BGRA8;
#else
    return SG_PIXELFORMAT_RGBA8;
#endif
}

#if defined(__EMSCRIPTEN__) && defined(SOKOL_WGPU)
struct RendererWgpuState {
    wgpu::Instance instance;
    wgpu::Adapter adapter;
    wgpu::Device device;
    wgpu::Queue queue;
    wgpu::Surface surface;
    wgpu::Texture depth_texture;
    wgpu::TextureView depth_view;
    wgpu::TextureView render_view;
    wgpu::SurfaceTexture surface_texture;
    int width;
    int height;
    bool configured;
};

static RendererWgpuState g_wgpu;

static const char* renderer_wgpu_string(wgpu::StringView s) {
    return s.data ? s.data : "";
}

static bool renderer_wgpu_configure_surface(int width, int height) {
    if (width <= 0 || height <= 0) return false;
    if (!g_wgpu.device || !g_wgpu.surface) return false;
    if (g_wgpu.configured && g_wgpu.width == width && g_wgpu.height == height) return true;

    g_wgpu.render_view = nullptr;
    g_wgpu.depth_view = nullptr;
    g_wgpu.depth_texture = nullptr;

    wgpu::SurfaceConfiguration cfg = {};
    cfg.device = g_wgpu.device;
    cfg.format = wgpu::TextureFormat::BGRA8Unorm;
    cfg.usage = wgpu::TextureUsage::RenderAttachment;
    cfg.width = (uint32_t)width;
    cfg.height = (uint32_t)height;
    cfg.presentMode = wgpu::PresentMode::Fifo;
    g_wgpu.surface.Configure(&cfg);

    wgpu::TextureDescriptor depth_desc = {};
    depth_desc.usage = wgpu::TextureUsage::RenderAttachment;
    depth_desc.dimension = wgpu::TextureDimension::e2D;
    depth_desc.size.width = (uint32_t)width;
    depth_desc.size.height = (uint32_t)height;
    depth_desc.size.depthOrArrayLayers = 1;
    depth_desc.format = wgpu::TextureFormat::Depth32FloatStencil8;
    depth_desc.mipLevelCount = 1;
    depth_desc.sampleCount = 1;
    g_wgpu.depth_texture = g_wgpu.device.CreateTexture(&depth_desc);
    if (!g_wgpu.depth_texture) {
        fprintf(stderr, "WebGPU: failed to create depth/stencil texture\n");
        return false;
    }
    g_wgpu.depth_view = g_wgpu.depth_texture.CreateView();
    if (!g_wgpu.depth_view) {
        fprintf(stderr, "WebGPU: failed to create depth/stencil texture view\n");
        return false;
    }

    g_wgpu.width = width;
    g_wgpu.height = height;
    g_wgpu.configured = true;
    return true;
}

bool renderer_wgpu_setup(const char* canvas_selector, int width, int height, sg_desc* desc) {
    if (!desc) return false;

    static constexpr wgpu::InstanceFeatureName instance_features[] = {
        wgpu::InstanceFeatureName::TimedWaitAny,
    };
    wgpu::InstanceDescriptor instance_desc = {};
    instance_desc.requiredFeatureCount = 1;
    instance_desc.requiredFeatures = instance_features;
    g_wgpu.instance = wgpu::CreateInstance(&instance_desc);
    if (!g_wgpu.instance) {
        fprintf(stderr, "WebGPU: failed to create instance\n");
        return false;
    }

    wgpu::RequestAdapterOptions adapter_opts = {};
    adapter_opts.featureLevel = wgpu::FeatureLevel::Core;
    adapter_opts.powerPreference = wgpu::PowerPreference::HighPerformance;
    g_wgpu.instance.WaitAny(
        g_wgpu.instance.RequestAdapter(
            &adapter_opts,
            wgpu::CallbackMode::WaitAnyOnly,
            [](wgpu::RequestAdapterStatus status, wgpu::Adapter adapter, wgpu::StringView message) {
                if (status != wgpu::RequestAdapterStatus::Success) {
                    fprintf(stderr, "WebGPU: requestAdapter failed: %s\n", renderer_wgpu_string(message));
                    return;
                }
                g_wgpu.adapter = std::move(adapter);
            }),
        UINT64_MAX);
    if (!g_wgpu.adapter) return false;

    if (!g_wgpu.adapter.HasFeature(wgpu::FeatureName::Depth32FloatStencil8)) {
        fprintf(stderr, "WebGPU: adapter does not support depth32float-stencil8\n");
        return false;
    }

    static constexpr wgpu::FeatureName required_features[] = {
        wgpu::FeatureName::Depth32FloatStencil8,
    };
    wgpu::Limits adapter_limits = {};
    g_wgpu.adapter.GetLimits(&adapter_limits);
    wgpu::Limits required_limits = {};
    required_limits.maxBufferSize = adapter_limits.maxBufferSize;
    required_limits.maxStorageBufferBindingSize = adapter_limits.maxStorageBufferBindingSize;
    wgpu::DeviceDescriptor device_desc = {};
    device_desc.requiredFeatureCount = 1;
    device_desc.requiredFeatures = required_features;
    device_desc.requiredLimits = &required_limits;
    device_desc.SetUncapturedErrorCallback(
        [](const wgpu::Device&, wgpu::ErrorType type, wgpu::StringView message) {
            fprintf(stderr, "WebGPU uncaptured error (%d): %s\n", (int)type, renderer_wgpu_string(message));
        });
    device_desc.SetDeviceLostCallback(
        wgpu::CallbackMode::AllowSpontaneous,
        [](const wgpu::Device&, wgpu::DeviceLostReason reason, wgpu::StringView message) {
            fprintf(stderr, "WebGPU device lost (%d): %s\n", (int)reason, renderer_wgpu_string(message));
        });
    g_wgpu.instance.WaitAny(
        g_wgpu.adapter.RequestDevice(
            &device_desc,
            wgpu::CallbackMode::WaitAnyOnly,
            [](wgpu::RequestDeviceStatus status, wgpu::Device device, wgpu::StringView message) {
                if (status != wgpu::RequestDeviceStatus::Success) {
                    fprintf(stderr, "WebGPU: requestDevice failed: %s\n", renderer_wgpu_string(message));
                    return;
                }
                g_wgpu.device = std::move(device);
                g_wgpu.queue = g_wgpu.device.GetQueue();
            }),
        UINT64_MAX);
    if (!g_wgpu.device) return false;

    wgpu::EmscriptenSurfaceSourceCanvasHTMLSelector canvas_desc = {};
    canvas_desc.selector = canvas_selector ? canvas_selector : "#canvas";
    wgpu::SurfaceDescriptor surface_desc = {};
    surface_desc.nextInChain = &canvas_desc;
    g_wgpu.surface = g_wgpu.instance.CreateSurface(&surface_desc);
    if (!g_wgpu.surface) {
        fprintf(stderr, "WebGPU: failed to create canvas surface\n");
        return false;
    }

    if (!renderer_wgpu_configure_surface(width, height)) return false;

    desc->environment.wgpu.device = g_wgpu.device.Get();
    desc->environment.defaults.color_format = renderer_default_color_format();
    desc->environment.defaults.depth_format = SG_PIXELFORMAT_DEPTH_STENCIL;
    desc->environment.defaults.sample_count = 1;
    return true;
}

static bool renderer_wgpu_fill_swapchain(sg_swapchain* swapchain, int width, int height) {
    if (!swapchain) return false;
    if (!renderer_wgpu_configure_surface(width, height)) return false;

    g_wgpu.render_view = nullptr;
    g_wgpu.surface_texture = {};
    g_wgpu.surface.GetCurrentTexture(&g_wgpu.surface_texture);
    if ((g_wgpu.surface_texture.status != wgpu::SurfaceGetCurrentTextureStatus::SuccessOptimal) &&
        (g_wgpu.surface_texture.status != wgpu::SurfaceGetCurrentTextureStatus::SuccessSuboptimal)) {
        fprintf(stderr, "WebGPU: failed to acquire surface texture (%d)\n", (int)g_wgpu.surface_texture.status);
        return false;
    }
    g_wgpu.render_view = g_wgpu.surface_texture.texture.CreateView();
    if (!g_wgpu.render_view) {
        fprintf(stderr, "WebGPU: failed to create surface texture view\n");
        return false;
    }

    swapchain->width = width;
    swapchain->height = height;
    swapchain->sample_count = 1;
    swapchain->color_format = renderer_default_color_format();
    swapchain->depth_format = SG_PIXELFORMAT_DEPTH_STENCIL;
    swapchain->wgpu.render_view = g_wgpu.render_view.Get();
    swapchain->wgpu.depth_stencil_view = g_wgpu.depth_view.Get();
    return true;
}

static void renderer_wgpu_present(void) {
    // emdawnwebgpu intentionally doesn't support wgpuSurfacePresent(); the
    // browser presents the current canvas texture at the requestAnimationFrame
    // boundary. Releasing our view/reference is enough for the next frame.
    g_wgpu.render_view = nullptr;
    g_wgpu.surface_texture = {};
}

void renderer_wgpu_shutdown(void) {
    g_wgpu.render_view = nullptr;
    g_wgpu.depth_view = nullptr;
    g_wgpu.depth_texture = nullptr;
    g_wgpu.surface = nullptr;
    g_wgpu.queue = nullptr;
    g_wgpu.device = nullptr;
    g_wgpu.adapter = nullptr;
    g_wgpu.instance = nullptr;
    g_wgpu = {};
}
#endif

static bool renderer_fill_default_swapchain(sg_swapchain* swapchain, int width, int height) {
#if defined(__EMSCRIPTEN__) && defined(SOKOL_WGPU)
    return renderer_wgpu_fill_swapchain(swapchain, width, height);
#else
    if (!swapchain) return false;
    swapchain->width = width;
    swapchain->height = height;
    swapchain->sample_count = 1;
    swapchain->color_format = renderer_default_color_format();
    swapchain->depth_format = SG_PIXELFORMAT_DEPTH_STENCIL;
    swapchain->gl.framebuffer = 0;
    return true;
#endif
}

static void renderer_present_default_swapchain(SDL_Window* window) {
#if defined(__EMSCRIPTEN__) && defined(SOKOL_WGPU)
    (void)window;
    renderer_wgpu_present();
#else
    SDL_GL_SwapWindow(window);
#endif
}

static void renderer_destroy_shader_pipeline(sg_pipeline* pipeline) {
    if (!pipeline->id) return;
    sg_pipeline_desc desc = sg_query_pipeline_desc(*pipeline);
    sg_destroy_pipeline(*pipeline);
    if (desc.shader.id) sg_destroy_shader(desc.shader);
    *pipeline = {};
}

static void renderer_destroy_shader_pipelines(Renderer* r) {
    renderer_destroy_shader_pipeline(&r->splat_pipeline);
    renderer_destroy_shader_pipeline(&r->splat_stochastic_pipeline);
    renderer_destroy_shader_pipeline(&r->accum_pipeline);
    renderer_destroy_shader_pipeline(&r->blit_pipeline);
    renderer_destroy_shader_pipeline(&r->overlay_pipeline);
    renderer_destroy_shader_pipeline(&r->darken_pipeline);
    renderer_destroy_shader_pipeline(&r->wireframe_pipeline);
    renderer_destroy_shader_pipeline(&r->mesh_pipeline);
}

static bool renderer_create_shader_pipelines(Renderer* r) {
    // --- Splat pipeline -------------------------------------------------
    {
        sg_pipeline_desc pd = {};
        pd.shader = sg_make_shader(splat_shader_desc(sg_query_backend()));
        pd.primitive_type = SG_PRIMITIVETYPE_TRIANGLES;
        // Per-instance attribute (uint splat_id) on buffer slot 0.
        pd.layout.buffers[0].stride = sizeof(uint32_t);
        pd.layout.buffers[0].step_func = SG_VERTEXSTEP_PER_INSTANCE;
        pd.layout.attrs[ATTR_splat_splat_id].buffer_index = 0;
        pd.layout.attrs[ATTR_splat_splat_id].offset = 0;
        pd.layout.attrs[ATTR_splat_splat_id].format = SG_VERTEXFORMAT_UINT;
        // Splats only test depth (so they don't poke through the mesh from
        // behind), they don't write depth or stencil.
        pd.depth.compare = SG_COMPAREFUNC_LESS;
        pd.depth.write_enabled = false;
        pd.depth.pixel_format = SG_PIXELFORMAT_DEPTH_STENCIL;
        pd.cull_mode = SG_CULLMODE_NONE;
        pd.colors[0].pixel_format = renderer_default_color_format();
        pd.colors[0].blend.enabled = true;
        pd.colors[0].blend.src_factor_rgb = SG_BLENDFACTOR_ONE;
        pd.colors[0].blend.dst_factor_rgb = SG_BLENDFACTOR_ONE_MINUS_SRC_ALPHA;
        pd.colors[0].blend.op_rgb = SG_BLENDOP_ADD;
        // Alpha factor preserves the previous behavior where the alpha
        // channel was scaled by a "blend constant" to control occlusion of
        // the wireframe pass. sokol_gfx has no equivalent of
        // SDL_SetGPUBlendConstants, so this stage now uses ONE/ONE-MINUS
        // for alpha — wireframe_occlusion is therefore no longer honored.
        pd.colors[0].blend.src_factor_alpha = SG_BLENDFACTOR_ONE;
        pd.colors[0].blend.dst_factor_alpha = SG_BLENDFACTOR_ONE_MINUS_SRC_ALPHA;
        pd.colors[0].blend.op_alpha = SG_BLENDOP_ADD;
        pd.colors[0].write_mask = SG_COLORMASK_RGBA;
        pd.label = "splat-pipeline";
        r->splat_pipeline = sg_make_pipeline(&pd);
    }

    // --- Stochastic splat pipeline --------------------------------------
    {
        sg_pipeline_desc pd = {};
        pd.shader = sg_make_shader(splat_stochastic_shader_desc(sg_query_backend()));
        pd.primitive_type = SG_PRIMITIVETYPE_TRIANGLES;
        pd.layout.buffers[0].stride = sizeof(uint32_t);
        pd.layout.buffers[0].step_func = SG_VERTEXSTEP_PER_INSTANCE;
        pd.layout.attrs[ATTR_splat_stochastic_splat_id].buffer_index = 0;
        pd.layout.attrs[ATTR_splat_stochastic_splat_id].offset = 0;
        pd.layout.attrs[ATTR_splat_stochastic_splat_id].format = SG_VERTEXFORMAT_UINT;
        pd.depth.compare = SG_COMPAREFUNC_LESS;
        pd.depth.write_enabled = true;
        pd.depth.pixel_format = SG_PIXELFORMAT_DEPTH_STENCIL;
        pd.cull_mode = SG_CULLMODE_NONE;
        pd.colors[0].pixel_format = renderer_default_color_format();
        pd.colors[0].blend.enabled = false;
        pd.colors[0].write_mask = SG_COLORMASK_RGBA;
        pd.label = "splat-stochastic-pipeline";
        r->splat_stochastic_pipeline = sg_make_pipeline(&pd);
    }

    // --- Fullscreen accumulation/display pipelines ----------------------
    {
        sg_pipeline_desc pd = {};
        pd.shader = sg_make_shader(accum_shader_desc(sg_query_backend()));
        pd.primitive_type = SG_PRIMITIVETYPE_TRIANGLES;
        pd.cull_mode = SG_CULLMODE_NONE;
        pd.depth.pixel_format = SG_PIXELFORMAT_NONE;
        pd.colors[0].pixel_format = renderer_default_color_format();
        pd.colors[0].blend.enabled = false;
        pd.colors[0].write_mask = SG_COLORMASK_RGBA;
        pd.label = "stochastic-accum-pipeline";
        r->accum_pipeline = sg_make_pipeline(&pd);
    }
    {
        sg_pipeline_desc pd = {};
        pd.shader = sg_make_shader(blit_shader_desc(sg_query_backend()));
        pd.primitive_type = SG_PRIMITIVETYPE_TRIANGLES;
        pd.cull_mode = SG_CULLMODE_NONE;
        pd.depth.pixel_format = SG_PIXELFORMAT_DEPTH_STENCIL;
        pd.colors[0].pixel_format = renderer_default_color_format();
        pd.colors[0].blend.enabled = false;
        pd.colors[0].write_mask = SG_COLORMASK_RGBA;
        pd.label = "stochastic-blit-pipeline";
        r->blit_pipeline = sg_make_pipeline(&pd);
    }

    // --- Overlay pipeline -----------------------------------------------
    {
        sg_pipeline_desc pd = {};
        pd.shader = sg_make_shader(overlay_shader_desc(sg_query_backend()));
        pd.primitive_type = SG_PRIMITIVETYPE_TRIANGLES;
        pd.cull_mode = SG_CULLMODE_NONE;
        pd.depth.pixel_format = SG_PIXELFORMAT_DEPTH_STENCIL;
        // Stencil: only draw where stencil != 1 (i.e. NOT inside the mesh
        // silhouette). Inside the mesh region, the mesh + splat composite
        // stays. ref value baked into the pipeline.
        pd.stencil.enabled = true;
        pd.stencil.read_mask = 0xFF;
        pd.stencil.write_mask = 0x00;
        pd.stencil.ref = 1;
        pd.stencil.front.compare = SG_COMPAREFUNC_NOT_EQUAL;
        pd.stencil.front.fail_op = SG_STENCILOP_KEEP;
        pd.stencil.front.depth_fail_op = SG_STENCILOP_KEEP;
        pd.stencil.front.pass_op = SG_STENCILOP_KEEP;
        pd.stencil.back = pd.stencil.front;
        pd.colors[0].pixel_format = renderer_default_color_format();
        pd.colors[0].blend.enabled = true;
        pd.colors[0].blend.src_factor_rgb = SG_BLENDFACTOR_ONE;
        pd.colors[0].blend.dst_factor_rgb = SG_BLENDFACTOR_ONE_MINUS_SRC_ALPHA;
        pd.colors[0].blend.op_rgb = SG_BLENDOP_ADD;
        pd.colors[0].blend.src_factor_alpha = SG_BLENDFACTOR_ONE;
        pd.colors[0].blend.dst_factor_alpha = SG_BLENDFACTOR_ONE_MINUS_SRC_ALPHA;
        pd.colors[0].blend.op_alpha = SG_BLENDOP_ADD;
        pd.colors[0].write_mask = (sg_color_mask)(SG_COLORMASK_R | SG_COLORMASK_G | SG_COLORMASK_B);
        pd.label = "overlay-pipeline";
        r->overlay_pipeline = sg_make_pipeline(&pd);
    }

    // --- Darken pipeline ------------------------------------------------
    // Fullscreen translucent black quad used to dim the FPS view behind the
    // top-down map overlay. Built even though the map_cam two-pass path is
    // disabled in this commit, so the pipeline is ready when it's restored.
    {
        sg_pipeline_desc pd = {};
        pd.shader = sg_make_shader(darken_shader_desc(sg_query_backend()));
        pd.primitive_type = SG_PRIMITIVETYPE_TRIANGLES;
        pd.cull_mode = SG_CULLMODE_NONE;
        pd.depth.pixel_format = SG_PIXELFORMAT_DEPTH_STENCIL;
        // No depth/stencil testing.
        pd.colors[0].pixel_format = renderer_default_color_format();
        pd.colors[0].blend.enabled = true;
        pd.colors[0].blend.src_factor_rgb = SG_BLENDFACTOR_ONE;
        pd.colors[0].blend.dst_factor_rgb = SG_BLENDFACTOR_ONE_MINUS_SRC_ALPHA;
        pd.colors[0].blend.op_rgb = SG_BLENDOP_ADD;
        pd.colors[0].blend.src_factor_alpha = SG_BLENDFACTOR_ONE;
        pd.colors[0].blend.dst_factor_alpha = SG_BLENDFACTOR_ONE_MINUS_SRC_ALPHA;
        pd.colors[0].blend.op_alpha = SG_BLENDOP_ADD;
        pd.colors[0].write_mask = (sg_color_mask)(SG_COLORMASK_R | SG_COLORMASK_G | SG_COLORMASK_B);
        pd.label = "darken-pipeline";
        r->darken_pipeline = sg_make_pipeline(&pd);
    }

    // --- Wireframe pipeline ---------------------------------------------
    {
        sg_pipeline_desc pd = {};
        pd.shader = sg_make_shader(wireframe_shader_desc(sg_query_backend()));
        pd.primitive_type = SG_PRIMITIVETYPE_LINES;
        pd.index_type = SG_INDEXTYPE_UINT16;
        pd.cull_mode = SG_CULLMODE_NONE;
        pd.layout.buffers[0].stride = 3 * sizeof(float);
        pd.layout.buffers[0].step_func = SG_VERTEXSTEP_PER_VERTEX;
        pd.layout.attrs[ATTR_wireframe_in_position].buffer_index = 0;
        pd.layout.attrs[ATTR_wireframe_in_position].offset = 0;
        pd.layout.attrs[ATTR_wireframe_in_position].format = SG_VERTEXFORMAT_FLOAT3;
        pd.depth.pixel_format = SG_PIXELFORMAT_DEPTH_STENCIL;
        pd.colors[0].pixel_format = renderer_default_color_format();
        pd.colors[0].blend.enabled = true;
        pd.colors[0].blend.src_factor_rgb = SG_BLENDFACTOR_ONE_MINUS_DST_ALPHA;
        pd.colors[0].blend.dst_factor_rgb = SG_BLENDFACTOR_ONE;
        pd.colors[0].blend.op_rgb = SG_BLENDOP_ADD;
        pd.colors[0].blend.src_factor_alpha = SG_BLENDFACTOR_ZERO;
        pd.colors[0].blend.dst_factor_alpha = SG_BLENDFACTOR_ONE;
        pd.colors[0].blend.op_alpha = SG_BLENDOP_ADD;
        pd.colors[0].write_mask = (sg_color_mask)(SG_COLORMASK_R | SG_COLORMASK_G | SG_COLORMASK_B);
        pd.label = "wireframe-pipeline";
        r->wireframe_pipeline = sg_make_pipeline(&pd);
    }

    // --- Mesh pipeline --------------------------------------------------
    {
        sg_pipeline_desc pd = {};
        pd.shader = sg_make_shader(mesh_shader_desc(sg_query_backend()));
        pd.primitive_type = SG_PRIMITIVETYPE_TRIANGLES;
        pd.index_type = SG_INDEXTYPE_UINT32;
        pd.cull_mode = SG_CULLMODE_BACK;
        pd.face_winding = SG_FACEWINDING_CW;
        pd.layout.buffers[0].stride = 5 * sizeof(float);   // vec3 pos + vec2 uv
        pd.layout.buffers[0].step_func = SG_VERTEXSTEP_PER_VERTEX;
        pd.layout.attrs[ATTR_mesh_in_position].buffer_index = 0;
        pd.layout.attrs[ATTR_mesh_in_position].offset = 0;
        pd.layout.attrs[ATTR_mesh_in_position].format = SG_VERTEXFORMAT_FLOAT3;
        pd.layout.attrs[ATTR_mesh_in_uv].buffer_index = 0;
        pd.layout.attrs[ATTR_mesh_in_uv].offset = 3 * sizeof(float);
        pd.layout.attrs[ATTR_mesh_in_uv].format = SG_VERTEXFORMAT_FLOAT2;
        pd.depth.compare = SG_COMPAREFUNC_LESS;
        pd.depth.write_enabled = true;
        pd.depth.pixel_format = SG_PIXELFORMAT_DEPTH_STENCIL;
        // Every mesh pixel writes 1 to stencil, marking the mesh region.
        // The overlay pass draws only where stencil != 1.
        pd.stencil.enabled = true;
        pd.stencil.read_mask = 0xFF;
        pd.stencil.write_mask = 0xFF;
        pd.stencil.ref = 1;
        pd.stencil.front.compare = SG_COMPAREFUNC_ALWAYS;
        pd.stencil.front.fail_op = SG_STENCILOP_KEEP;
        pd.stencil.front.depth_fail_op = SG_STENCILOP_KEEP;
        pd.stencil.front.pass_op = SG_STENCILOP_REPLACE;
        pd.stencil.back = pd.stencil.front;
        pd.colors[0].pixel_format = renderer_default_color_format();
        pd.colors[0].blend.enabled = false;
        pd.colors[0].write_mask = SG_COLORMASK_RGBA;
        pd.label = "mesh-pipeline";
        r->mesh_pipeline = sg_make_pipeline(&pd);
    }

    bool ok = r->splat_pipeline.id && r->splat_stochastic_pipeline.id &&
              r->accum_pipeline.id && r->blit_pipeline.id && r->overlay_pipeline.id &&
              r->darken_pipeline.id && r->wireframe_pipeline.id &&
              r->mesh_pipeline.id;
    if (!ok) {
        fprintf(stderr, "renderer_create_shader_pipelines failed\n");
        renderer_destroy_shader_pipelines(r);
    }
    return ok;
}

bool renderer_reload_shaders(Renderer* r) {
    renderer_destroy_shader_pipelines(r);
    bool ok = renderer_create_shader_pipelines(r);
    if (ok) fprintf(stderr, "Renderer shaders reloaded\n");
    return ok;
}

bool renderer_init(Renderer* r, SDL_Window* window) {
    memset(r, 0, sizeof(*r));
    r->window = window;
    r->splat_render_mode = SplatRenderMode::AlphaBlendSorted;
    r->stochastic_samples_per_frame = 1;
    r->stochastic_accumulation_enabled = true;
    r->mesh_transform.scale = 1.0f;
    r->object_transform.scale = 1.0f;
    PROFILE_GPU_CONTEXT();

    if (!renderer_create_shader_pipelines(r)) {
        return false;
    }

    // --- Samplers -------------------------------------------------------
    {
        sg_sampler_desc sd = {};
        sd.min_filter = SG_FILTER_LINEAR;
        sd.mag_filter = SG_FILTER_LINEAR;
        sd.mipmap_filter = SG_FILTER_NEAREST;
        sd.wrap_u = SG_WRAP_REPEAT;
        sd.wrap_v = SG_WRAP_CLAMP_TO_EDGE;
        sd.wrap_w = SG_WRAP_CLAMP_TO_EDGE;
        sd.label = "overlay-sampler";
        r->overlay_sampler = sg_make_sampler(&sd);
    }
    {
        sg_sampler_desc sd = {};
        sd.min_filter = SG_FILTER_NEAREST;
        sd.mag_filter = SG_FILTER_NEAREST;
        sd.mipmap_filter = SG_FILTER_NEAREST;
        sd.wrap_u = SG_WRAP_REPEAT;
        sd.wrap_v = SG_WRAP_REPEAT;
        sd.wrap_w = SG_WRAP_REPEAT;
        sd.label = "mesh-sampler";
        r->mesh_sampler = sg_make_sampler(&sd);
    }
    {
        sg_sampler_desc sd = {};
        sd.min_filter = SG_FILTER_NEAREST;
        sd.mag_filter = SG_FILTER_NEAREST;
        sd.mipmap_filter = SG_FILTER_NEAREST;
        sd.wrap_u = SG_WRAP_CLAMP_TO_EDGE;
        sd.wrap_v = SG_WRAP_CLAMP_TO_EDGE;
        sd.wrap_w = SG_WRAP_CLAMP_TO_EDGE;
        sd.label = "accum-sampler";
        r->accum_sampler = sg_make_sampler(&sd);
    }

    // --- Cube geometry (unit cube centered at origin, ±0.5) -------------
    static const float cube_verts[8 * 3] = {
        -0.5f, -0.5f, -0.5f,
         0.5f, -0.5f, -0.5f,
         0.5f,  0.5f, -0.5f,
        -0.5f,  0.5f, -0.5f,
        -0.5f, -0.5f,  0.5f,
         0.5f, -0.5f,  0.5f,
         0.5f,  0.5f,  0.5f,
        -0.5f,  0.5f,  0.5f,
    };
    static const uint16_t cube_indices[24] = {
        0,1, 1,2, 2,3, 3,0,
        4,5, 5,6, 6,7, 7,4,
        0,4, 1,5, 2,6, 3,7,
    };
    {
        sg_buffer_desc bd = {};
        bd.usage.vertex_buffer = true;
        bd.data = SG_RANGE(cube_verts);
        bd.label = "cube-vb";
        r->cube_vertex_buffer = sg_make_buffer(&bd);
    }
    {
        sg_buffer_desc bd = {};
        bd.usage.index_buffer = true;
        bd.data = SG_RANGE(cube_indices);
        bd.label = "cube-ib";
        r->cube_index_buffer = sg_make_buffer(&bd);
    }

    fprintf(stderr, "Renderer init OK\n");
    return true;
}

// Gaussian texture layout: each gaussian occupies 16 consecutive RGBA32F
// texels (= 64 floats, same byte layout as GpuGaussian). Width is fixed at
// 4096 (POT, so the shader can use bit ops). Height grows to hold N gaussians.
#define GAUSSIAN_TEX_WIDTH      4096u
#define GAUSSIAN_TEXELS_PER     16u
#define GAUSSIAN_BYTES_PER_TEXEL 16u  // RGBA32F

void renderer_upload_gaussians(Renderer* r, const GaussianScene* scene) {
    r->gaussian_count = scene->gaussian_count;
    renderer_reset_stochastic_accumulation(r);

    if (r->gaussian_buffer_view.id) {
        sg_destroy_view(r->gaussian_buffer_view);
        r->gaussian_buffer_view = {};
    }
    if (r->gaussian_buffer.id) {
        sg_destroy_buffer(r->gaussian_buffer);
        r->gaussian_buffer = {};
    }

    uint32_t total_texels = scene->gaussian_count * GAUSSIAN_TEXELS_PER;
    uint32_t tex_w = GAUSSIAN_TEX_WIDTH;
    uint32_t tex_h = (total_texels + tex_w - 1u) / tex_w;
    r->gaussian_tex_w = tex_w;
    r->gaussian_tex_h = tex_h;

    // Pack into the shader's storage-buffer struct layout.
    uint32_t payload_size = scene->gaussian_count * (uint32_t)sizeof(GpuGaussian);
    GpuGaussian* gpu_data = pack_gpu_gaussians(scene);

    sg_buffer_desc gbd = {};
    gbd.usage.storage_buffer = true;
    gbd.size = payload_size;
    gbd.data.ptr = gpu_data;
    gbd.data.size = payload_size;
    gbd.label = "gaussian-buffer";
    r->gaussian_buffer = sg_make_buffer(&gbd);
    free(gpu_data);

    sg_view_desc vd = {};
    vd.storage_buffer.buffer = r->gaussian_buffer;
    vd.label = "gaussian-buffer-view";
    r->gaussian_buffer_view = sg_make_view(&vd);

    // Dynamic per-instance sorted-index buffer (one uint per gaussian).
    sg_buffer_desc bd = {};
    bd.usage.vertex_buffer = true;
    bd.usage.stream_update = true;
    bd.size = scene->gaussian_count * sizeof(uint32_t);
    bd.label = "splat-index-vb";
    r->index_buffer = sg_make_buffer(&bd);
    r->index_buffer_capacity = scene->gaussian_count;

    // Dynamic per-instance unsorted visible-index buffer. In stochastic mode
    // this is updated from culling output directly (no depth sort), preserving
    // frustum culling while avoiding per-frame sort order.
    sg_buffer_desc ubd = {};
    ubd.usage.vertex_buffer = true;
    ubd.usage.stream_update = true;
    ubd.size = scene->gaussian_count * sizeof(uint32_t);
    ubd.label = "splat-unsorted-visible-index-vb";
    r->unsorted_index_buffer = sg_make_buffer(&ubd);

    fprintf(stderr, "Uploaded %u gaussians (storage buffer = %u bytes, old texture footprint = %ux%u RGBA32F)\n",
            scene->gaussian_count, payload_size, tex_w, tex_h);
}

// Release everything held by a MeshGpu and zero it. Safe to call on an
// already-empty MeshGpu (all fields NULL/0).
static void mesh_gpu_release(MeshGpu* m) {
    if (m->vertex_buffer.id) sg_destroy_buffer(m->vertex_buffer);
    if (m->index_buffer.id)  sg_destroy_buffer(m->index_buffer);
    if (m->textures) {
        for (uint32_t i = 0; i < m->texture_count; ++i) {
            if (m->texture_views && m->texture_views[i].id) sg_destroy_view(m->texture_views[i]);
            if (m->textures[i].id) sg_destroy_image(m->textures[i]);
        }
        free(m->textures);
        free(m->texture_views);
    }
    if (m->default_texture_view.id) sg_destroy_view(m->default_texture_view);
    if (m->default_texture.id)      sg_destroy_image(m->default_texture);
    if (m->submeshes) free(m->submeshes);
    memset(m, 0, sizeof(*m));
}

// Upload mesh geometry, textures, and submesh metadata to `out`. Replaces any
// existing GPU resources in `out`. Returns true on success.
static bool mesh_gpu_upload(const Mesh* mesh, MeshGpu* out) {
    mesh_gpu_release(out);

    uint32_t vert_count  = mesh->vertex_count;
    uint32_t index_count = mesh->index_count;
    uint32_t vb_size = vert_count * 5 * sizeof(float); // vec3 pos + vec2 uv
    uint32_t ib_size = index_count * sizeof(uint32_t);

    {
        sg_buffer_desc bd = {};
        bd.usage.vertex_buffer = true;
        bd.data.ptr = mesh->vertices;
        bd.data.size = vb_size;
        bd.label = "mesh-vb";
        out->vertex_buffer = sg_make_buffer(&bd);
    }
    {
        sg_buffer_desc bd = {};
        bd.usage.index_buffer = true;
        bd.data.ptr = mesh->indices;
        bd.data.size = ib_size;
        bd.label = "mesh-ib";
        out->index_buffer = sg_make_buffer(&bd);
    }

    // Default 1x1 white texture (fallback for submeshes without a material).
    {
        static const uint8_t white_px[4] = { 255, 255, 255, 255 };
        sg_image_desc id = {};
        id.type = SG_IMAGETYPE_2D;
        id.width = 1;
        id.height = 1;
        id.num_slices = 1;
        id.num_mipmaps = 1;
        id.pixel_format = SG_PIXELFORMAT_RGBA8;
        id.data.mip_levels[0].ptr = white_px;
        id.data.mip_levels[0].size = sizeof(white_px);
        id.label = "mesh-default-tex";
        out->default_texture = sg_make_image(&id);

        sg_view_desc vd = {};
        vd.texture.image = out->default_texture;
        vd.label = "mesh-default-tex-view";
        out->default_texture_view = sg_make_view(&vd);
    }

    // Per-material textures.
    if (mesh->texture_count > 0) {
        out->textures = (sg_image*)calloc(mesh->texture_count, sizeof(sg_image));
        out->texture_views = (sg_view*)calloc(mesh->texture_count, sizeof(sg_view));
        out->texture_count = mesh->texture_count;
        for (uint32_t i = 0; i < mesh->texture_count; ++i) {
            const MeshTexture& mt = mesh->textures[i];
            sg_image_desc id = {};
            id.type = SG_IMAGETYPE_2D;
            id.width = mt.w;
            id.height = mt.h;
            id.num_slices = 1;
            id.num_mipmaps = 1;
            id.pixel_format = SG_PIXELFORMAT_RGBA8;
            id.data.mip_levels[0].ptr = mt.rgba;
            id.data.mip_levels[0].size = (size_t)mt.w * (size_t)mt.h * 4u;
            id.label = "mesh-tex";
            out->textures[i] = sg_make_image(&id);

            sg_view_desc vd = {};
            vd.texture.image = out->textures[i];
            vd.label = "mesh-tex-view";
            out->texture_views[i] = sg_make_view(&vd);
        }
    }

    // Copy submesh metadata.
    out->submesh_count = mesh->submesh_count;
    if (mesh->submesh_count > 0) {
        out->submeshes = (MeshSubmesh*)malloc(mesh->submesh_count * sizeof(MeshSubmesh));
        memcpy(out->submeshes, mesh->submeshes, mesh->submesh_count * sizeof(MeshSubmesh));
    }

    fprintf(stderr, "Uploaded mesh: %u verts, %u indices, %u textures, %u submeshes\n",
            vert_count, index_count, mesh->texture_count, mesh->submesh_count);

    return true;
}

bool renderer_upload_mesh(Renderer* r, const Mesh* mesh) {
    return mesh_gpu_upload(mesh, &r->mesh_gpu);
}

bool renderer_upload_object_mesh(Renderer* r, const Mesh* mesh) {
    return mesh_gpu_upload(mesh, &r->object_gpu);
}

// Build column-major model matrix: T * Rz * Ry * Rx * S (intrinsic Z-Y-X Euler).
static void mat4_from_transform(const MeshTransform& t, float* out) {
    float cx = cosf(t.rotation_euler[0]), sx = sinf(t.rotation_euler[0]);
    float cy = cosf(t.rotation_euler[1]), sy = sinf(t.rotation_euler[1]);
    float cz = cosf(t.rotation_euler[2]), sz = sinf(t.rotation_euler[2]);
    float s = t.scale;

    float r00 = cy * cz;
    float r01 = sx * sy * cz - cx * sz;
    float r02 = cx * sy * cz + sx * sz;
    float r10 = cy * sz;
    float r11 = sx * sy * sz + cx * cz;
    float r12 = cx * sy * sz - sx * cz;
    float r20 = -sy;
    float r21 = sx * cy;
    float r22 = cx * cy;

    out[0]  = r00 * s; out[1]  = r10 * s; out[2]  = r20 * s; out[3]  = 0.0f;
    out[4]  = r01 * s; out[5]  = r11 * s; out[6]  = r21 * s; out[7]  = 0.0f;
    out[8]  = r02 * s; out[9]  = r12 * s; out[10] = r22 * s; out[11] = 0.0f;
    out[12] = t.translation[0];
    out[13] = t.translation[1];
    out[14] = t.translation[2];
    out[15] = 1.0f;
}

void renderer_reset_stochastic_accumulation(Renderer* r) {
    r->stochastic_sample_count = 0;
    r->stochastic_accum_write_index = 0;
    r->stochastic_prev_cam_valid = false;
    r->stochastic_prev_effect_valid = false;
}

static void renderer_destroy_stochastic_targets(Renderer* r) {
    if (r->stochastic_sample_texture_view.id) sg_destroy_view(r->stochastic_sample_texture_view);
    if (r->stochastic_sample_color_view.id)   sg_destroy_view(r->stochastic_sample_color_view);
    if (r->stochastic_sample_image.id)        sg_destroy_image(r->stochastic_sample_image);
    if (r->stochastic_depth_view.id)          sg_destroy_view(r->stochastic_depth_view);
    if (r->stochastic_depth_image.id)         sg_destroy_image(r->stochastic_depth_image);
    for (int i = 0; i < 2; ++i) {
        if (r->stochastic_accum_texture_views[i].id) sg_destroy_view(r->stochastic_accum_texture_views[i]);
        if (r->stochastic_accum_color_views[i].id)   sg_destroy_view(r->stochastic_accum_color_views[i]);
        if (r->stochastic_accum_images[i].id)        sg_destroy_image(r->stochastic_accum_images[i]);
        r->stochastic_accum_texture_views[i] = {};
        r->stochastic_accum_color_views[i] = {};
        r->stochastic_accum_images[i] = {};
    }
    r->stochastic_sample_texture_view = {};
    r->stochastic_sample_color_view = {};
    r->stochastic_sample_image = {};
    r->stochastic_depth_view = {};
    r->stochastic_depth_image = {};
    r->stochastic_width = 0;
    r->stochastic_height = 0;
    renderer_reset_stochastic_accumulation(r);
}

static sg_view make_texture_view(sg_image image, const char* label) {
    sg_view_desc vd = {};
    vd.texture.image = image;
    vd.label = label;
    return sg_make_view(&vd);
}

static sg_view make_color_attachment_view(sg_image image, const char* label) {
    sg_view_desc vd = {};
    vd.color_attachment.image = image;
    vd.label = label;
    return sg_make_view(&vd);
}

static bool renderer_ensure_stochastic_targets(Renderer* r, int width, int height) {
    if (width <= 0 || height <= 0) return false;
    if (r->stochastic_width == (uint32_t)width && r->stochastic_height == (uint32_t)height &&
        r->stochastic_sample_image.id && r->stochastic_depth_image.id &&
        r->stochastic_accum_images[0].id && r->stochastic_accum_images[1].id) {
        return true;
    }

    renderer_destroy_stochastic_targets(r);

    sg_image_desc color_desc = {};
    color_desc.type = SG_IMAGETYPE_2D;
    color_desc.usage.color_attachment = true;
    color_desc.width = width;
    color_desc.height = height;
    color_desc.num_slices = 1;
    color_desc.num_mipmaps = 1;
    color_desc.pixel_format = renderer_default_color_format();
    color_desc.sample_count = 1;

    color_desc.label = "stochastic-sample-color";
    r->stochastic_sample_image = sg_make_image(&color_desc);
    r->stochastic_sample_color_view = make_color_attachment_view(r->stochastic_sample_image, "stochastic-sample-color-att-view");
    r->stochastic_sample_texture_view = make_texture_view(r->stochastic_sample_image, "stochastic-sample-tex-view");

    for (int i = 0; i < 2; ++i) {
        color_desc.label = i == 0 ? "stochastic-accum-a" : "stochastic-accum-b";
        r->stochastic_accum_images[i] = sg_make_image(&color_desc);
        r->stochastic_accum_color_views[i] = make_color_attachment_view(r->stochastic_accum_images[i], i == 0 ? "stochastic-accum-a-att-view" : "stochastic-accum-b-att-view");
        r->stochastic_accum_texture_views[i] = make_texture_view(r->stochastic_accum_images[i], i == 0 ? "stochastic-accum-a-tex-view" : "stochastic-accum-b-tex-view");
    }

    sg_image_desc depth_desc = {};
    depth_desc.type = SG_IMAGETYPE_2D;
    depth_desc.usage.depth_stencil_attachment = true;
    depth_desc.width = width;
    depth_desc.height = height;
    depth_desc.num_slices = 1;
    depth_desc.num_mipmaps = 1;
    depth_desc.pixel_format = SG_PIXELFORMAT_DEPTH_STENCIL;
    depth_desc.sample_count = 1;
    depth_desc.label = "stochastic-depth-stencil";
    r->stochastic_depth_image = sg_make_image(&depth_desc);

    sg_view_desc dvd = {};
    dvd.depth_stencil_attachment.image = r->stochastic_depth_image;
    dvd.label = "stochastic-depth-stencil-att-view";
    r->stochastic_depth_view = sg_make_view(&dvd);

    r->stochastic_width = (uint32_t)width;
    r->stochastic_height = (uint32_t)height;
    renderer_reset_stochastic_accumulation(r);

    return r->stochastic_sample_image.id && r->stochastic_sample_color_view.id &&
           r->stochastic_sample_texture_view.id && r->stochastic_depth_image.id &&
           r->stochastic_depth_view.id && r->stochastic_accum_images[0].id &&
           r->stochastic_accum_images[1].id && r->stochastic_accum_color_views[0].id &&
           r->stochastic_accum_color_views[1].id && r->stochastic_accum_texture_views[0].id &&
           r->stochastic_accum_texture_views[1].id;
}

// Draws mesh + splats + (optional) panorama overlay + (optional) wireframe
// nodes for one camera into the currently-active sg_begin_pass. ImGui is NOT
// drawn here; the caller is responsible for that after this returns.
static void draw_world(Renderer* r, const GaussianScene* scene, const CameraUniforms* cam,
                       const OverlayParams* overlay, const NodeRenderParams* nodes,
                       const SplatEffectParams* splat_effect, SplatRenderMode splat_mode) {
    // VP shared by both mesh slots and the wireframe pass.
    float vp[16];
    math_mat4_mul(cam->proj, cam->view, vp);

    // Mesh: writes color, depth, and stencil=1 to mark its silhouette. Same
    // lambda is reused for the static --object mesh (with its own MVP).
    auto draw_mesh_slot = [&](const MeshGpu* m, const float* mvp) {
        if (m->vertex_buffer.id == 0 || m->index_buffer.id == 0 || m->submesh_count == 0) return;

        sg_apply_pipeline(r->mesh_pipeline);

        for (uint32_t i = 0; i < m->submesh_count; ++i) {
            const MeshSubmesh& sm = m->submeshes[i];
            if (sm.index_count == 0) continue;

            sg_view tex_view = m->default_texture_view;
            float use_texture = 0.0f;
            if (sm.texture_id >= 0 && (uint32_t)sm.texture_id < m->texture_count
                && m->textures[sm.texture_id].id) {
                tex_view = m->texture_views[sm.texture_id];
                use_texture = 1.0f;
            }

            sg_bindings bnd = {};
            bnd.vertex_buffers[0] = m->vertex_buffer;
            bnd.index_buffer = m->index_buffer;
            bnd.views[VIEW_mesh_tex] = tex_view;
            bnd.samplers[SMP_mesh_smp] = r->mesh_sampler;
            sg_apply_bindings(&bnd);

            MeshUniforms_t u = {};
            memcpy(u.mvp, mvp, sizeof(u.mvp));
            u.color[0] = u.color[1] = u.color[2] = u.color[3] = 1.0f;
            u.use_texture = use_texture;
            sg_apply_uniforms(UB_MeshUniforms, SG_RANGE_REF(u));

            sg_draw((int)sm.index_offset, (int)sm.index_count, 1);
        }
    };

    PROFILE("render mesh pass") {
    PROFILE_GPU("mesh pass") {
    // Primary animated mesh.
    {
        float model[16];
        mat4_from_transform(r->mesh_transform, model);
        float mvp[16];
        math_mat4_mul(vp, model, mvp);
        draw_mesh_slot(&r->mesh_gpu, mvp);
    }

    // Static --object mesh (transformed by object_transform; identity by default).
    if (r->object_gpu.vertex_buffer.id) {
        float obj_model[16];
        mat4_from_transform(r->object_transform, obj_model);
        float obj_mvp[16];
        math_mat4_mul(vp, obj_model, obj_mvp);
        draw_mesh_slot(&r->object_gpu, obj_mvp);
    }
    }
    }

    // Splats
    sg_buffer splat_id_buffer = (splat_mode == SplatRenderMode::StochasticUnsorted)
        ? r->unsorted_index_buffer
        : r->index_buffer;
    if (scene->visible_count > 0 && r->gaussian_buffer.id && splat_id_buffer.id) {
        PROFILE("render splat pass") {
        PROFILE_GPU("splat pass") {
        sg_apply_pipeline(splat_mode == SplatRenderMode::StochasticUnsorted
            ? r->splat_stochastic_pipeline
            : r->splat_pipeline);

        sg_bindings bnd = {};
        bnd.vertex_buffers[0] = splat_id_buffer;
        bnd.views[VIEW_gaussian_buf] = r->gaussian_buffer_view;
        sg_apply_bindings(&bnd);

        // The CameraUniforms host struct lays out 1:1 with the generated
        // CameraUBO_t (verified by the existing usage in main.cpp).
        sg_apply_uniforms(UB_CameraUBO, sg_range{ cam, sizeof(CameraUniforms) });
        SplatEffectUBO_t effect_ubo = {};
        if (splat_effect) {
            memcpy(effect_ubo.effect_center_radius, splat_effect->center_radius, sizeof(effect_ubo.effect_center_radius));
            memcpy(effect_ubo.effect_params, splat_effect->params, sizeof(effect_ubo.effect_params));
            memcpy(effect_ubo.effect_color, splat_effect->color, sizeof(effect_ubo.effect_color));
        }
        sg_apply_uniforms(UB_SplatEffectUBO, SG_RANGE_REF(effect_ubo));
        if (splat_mode == SplatRenderMode::StochasticUnsorted) {
            StochasticUBO_t stochastic_ubo = {};
            stochastic_ubo.frame_seed = (float)r->stochastic_frame_seed;
            sg_apply_uniforms(UB_StochasticUBO, SG_RANGE_REF(stochastic_ubo));
        }

        // 6 vertices per quad, scene->visible_count instances.
        sg_draw(0, 6, (int)scene->visible_count);
        }
        }
    }

    // Equirectangular panorama overlay.
    if (overlay && overlay->texture.id && overlay->alpha > 0.0f) {
        PROFILE("render overlay pass") {
        PROFILE_GPU("overlay pass") {
        sg_apply_pipeline(r->overlay_pipeline);

        sg_bindings bnd = {};
        bnd.views[VIEW_panorama_tex] = overlay->texture_view;
        bnd.samplers[SMP_panorama_smp] = r->overlay_sampler;
        sg_apply_bindings(&bnd);

        OverlayUniforms_t u = {};
        memcpy(u.camera_ray_basis, overlay->camera_ray_basis, sizeof(u.camera_ray_basis));
        memcpy(u.camera_tan_half_fov, overlay->camera_tan_half_fov, sizeof(u.camera_tan_half_fov));
        memcpy(u.ref_rotation, overlay->ref_rotation, sizeof(u.ref_rotation));
        u.alpha = overlay->alpha;
        sg_apply_uniforms(UB_OverlayUniforms, SG_RANGE_REF(u));

        sg_draw(0, 3, 1); // fullscreen triangle
        }
        }
    }

    // Wireframe node cubes.
    if (nodes && nodes->count > 0) {
        PROFILE("render wireframe pass") {
        PROFILE_GPU("wireframe pass") {
        sg_apply_pipeline(r->wireframe_pipeline);

        float scale = nodes->half_size * 2.0f;
        for (uint32_t i = 0; i < nodes->count; i++) {
            const float* p = &nodes->positions[i * 3];

            sg_bindings bnd = {};
            bnd.vertex_buffers[0] = r->cube_vertex_buffer;
            bnd.index_buffer = r->cube_index_buffer;
            sg_apply_bindings(&bnd);

            float model[16];
            math_mat4_translate_scale(p[0], p[1], p[2], scale, model);
            float mvp[16];
            math_mat4_mul(vp, model, mvp);

            WireframeUniforms_t u = {};
            memcpy(u.mvp, mvp, sizeof(u.mvp));
            u.color[0] = 0.0f; u.color[1] = 1.0f; u.color[2] = 1.0f; u.color[3] = 1.0f;
            sg_apply_uniforms(UB_WireframeUniforms, SG_RANGE_REF(u));

            sg_draw(0, 24, 1);
        }
        }
        }
    }
}

void renderer_draw_frame(Renderer* r, GaussianScene* scene, const CameraUniforms* cam,
                         const OverlayParams* overlay, const NodeRenderParams* nodes,
                         const SplatEffectParams* splat_effect,
                         float wireframe_occlusion, const CameraUniforms* map_cam) {
    (void)wireframe_occlusion; // see splat-pipeline blend comment in renderer_init
    (void)map_cam;             // TODO: restore the two-pass top-down map overlay in a later commit

    const bool stochastic = (r->splat_render_mode == SplatRenderMode::StochasticUnsorted);

    // Push fresh visible IDs to the GPU once per frame. Alpha blend uses
    // depth-sorted IDs; stochastic mode deliberately keeps culling order
    // unsorted and skips the sorted-index buffer entirely.
    if (!stochastic && scene->visible_count > 0 && r->index_buffer.id) {
        PROFILE("update sorted index buffer") {
        sg_range range;
        range.ptr = scene->sorted_indices;
        range.size = scene->visible_count * sizeof(uint32_t);
        sg_update_buffer(r->index_buffer, &range);
        }
    } else if (stochastic && scene->visible_count > 0 && r->unsorted_index_buffer.id) {
        PROFILE("update unsorted visible index buffer") {
        sg_range range;
        range.ptr = scene->visible_indices;
        range.size = scene->visible_count * sizeof(uint32_t);
        sg_update_buffer(r->unsorted_index_buffer, &range);
        }
    }

    int win_w = 0, win_h = 0;
    SDL_GetWindowSize(r->window, &win_w, &win_h);

    if (stochastic) {
        if (!renderer_ensure_stochastic_targets(r, win_w, win_h)) {
            fprintf(stderr, "Failed to create stochastic render targets\n");
            return;
        }

        SplatEffectParams empty_effect = {};
        const SplatEffectParams* effect_for_compare = splat_effect ? splat_effect : &empty_effect;
        if ((r->stochastic_prev_cam_valid && memcmp(&r->stochastic_prev_cam, cam, sizeof(*cam)) != 0) ||
            (r->stochastic_prev_effect_valid && memcmp(&r->stochastic_prev_effect, effect_for_compare, sizeof(*effect_for_compare)) != 0)) {
            renderer_reset_stochastic_accumulation(r);
        }
        memcpy(&r->stochastic_prev_cam, cam, sizeof(*cam));
        memcpy(&r->stochastic_prev_effect, effect_for_compare, sizeof(*effect_for_compare));
        r->stochastic_prev_cam_valid = true;
        r->stochastic_prev_effect_valid = true;
        uint32_t samples_per_frame = r->stochastic_samples_per_frame;
        if (samples_per_frame < 1) samples_per_frame = 1;
        if (samples_per_frame > 16) samples_per_frame = 16;

        uint32_t write_index = r->stochastic_accum_write_index & 1u;
        bool display_accum_texture = false;
        for (uint32_t sample_i = 0; sample_i < samples_per_frame; ++sample_i) {
            r->stochastic_frame_seed++;

            sg_pass sample_pass = {};
            sample_pass.action.colors[0].load_action = SG_LOADACTION_CLEAR;
            sample_pass.action.colors[0].store_action = SG_STOREACTION_STORE;
            sample_pass.action.colors[0].clear_value = { 0.1f, 0.1f, 0.1f, 0.0f };
            sample_pass.action.depth.load_action = SG_LOADACTION_CLEAR;
            sample_pass.action.depth.store_action = SG_STOREACTION_DONTCARE;
            sample_pass.action.depth.clear_value = 1.0f;
            sample_pass.action.stencil.load_action = SG_LOADACTION_CLEAR;
            sample_pass.action.stencil.store_action = SG_STOREACTION_DONTCARE;
            sample_pass.action.stencil.clear_value = 0;
            sample_pass.attachments.colors[0] = r->stochastic_sample_color_view;
            sample_pass.attachments.depth_stencil = r->stochastic_depth_view;

            sg_begin_pass(&sample_pass);
            draw_world(r, scene, cam, overlay, nodes, splat_effect, SplatRenderMode::StochasticUnsorted);
            sg_end_pass();

            if (r->stochastic_accumulation_enabled || samples_per_frame > 1) {
                uint32_t next_sample_count = r->stochastic_accumulation_enabled
                    ? r->stochastic_sample_count + 1
                    : sample_i + 1;
                write_index = r->stochastic_accumulation_enabled
                    ? (r->stochastic_accum_write_index & 1u)
                    : (sample_i & 1u);
                uint32_t read_index = (write_index + 1u) & 1u;

                sg_pass accum_pass = {};
                accum_pass.action.colors[0].load_action = (next_sample_count == 1) ? SG_LOADACTION_CLEAR : SG_LOADACTION_DONTCARE;
                accum_pass.action.colors[0].store_action = SG_STOREACTION_STORE;
                accum_pass.action.colors[0].clear_value = { 0.1f, 0.1f, 0.1f, 0.0f };
                accum_pass.attachments.colors[0] = r->stochastic_accum_color_views[write_index];
                sg_begin_pass(&accum_pass);
                sg_apply_pipeline(r->accum_pipeline);
                sg_bindings accum_bnd = {};
                accum_bnd.views[VIEW_sample_tex] = r->stochastic_sample_texture_view;
                accum_bnd.samplers[SMP_sample_smp] = r->accum_sampler;
                accum_bnd.views[VIEW_history_tex] = (next_sample_count == 1)
                    ? r->stochastic_sample_texture_view
                    : r->stochastic_accum_texture_views[read_index];
                accum_bnd.samplers[SMP_history_smp] = r->accum_sampler;
                sg_apply_bindings(&accum_bnd);
                AccumUBO_t accum_ubo = {};
                accum_ubo.sample_count = (float)next_sample_count;
                sg_apply_uniforms(UB_AccumUBO, SG_RANGE_REF(accum_ubo));
                sg_draw(0, 3, 1);
                sg_end_pass();

                display_accum_texture = true;
                if (r->stochastic_accumulation_enabled) {
                    r->stochastic_sample_count = next_sample_count;
                    r->stochastic_accum_write_index = (write_index + 1u) & 1u;
                }
            }
        }

        sg_pass pass = {};
        pass.action.colors[0].load_action = SG_LOADACTION_CLEAR;
        pass.action.colors[0].store_action = SG_STOREACTION_STORE;
        pass.action.colors[0].clear_value = { 0.1f, 0.1f, 0.1f, 0.0f };
        pass.action.depth.load_action = SG_LOADACTION_CLEAR;
        pass.action.depth.store_action = SG_STOREACTION_DONTCARE;
        pass.action.depth.clear_value = 1.0f;
        pass.action.stencil.load_action = SG_LOADACTION_CLEAR;
        pass.action.stencil.store_action = SG_STOREACTION_DONTCARE;
        pass.action.stencil.clear_value = 0;
        if (!renderer_fill_default_swapchain(&pass.swapchain, win_w, win_h)) {
            fprintf(stderr, "Failed to acquire default swapchain\n");
            return;
        }

        sg_begin_pass(&pass);
        sg_apply_pipeline(r->blit_pipeline);
        sg_bindings blit_bnd = {};
        blit_bnd.views[VIEW_display_tex] = display_accum_texture
            ? r->stochastic_accum_texture_views[write_index]
            : r->stochastic_sample_texture_view;
        blit_bnd.samplers[SMP_display_smp] = r->accum_sampler;
        sg_apply_bindings(&blit_bnd);
        sg_draw(0, 3, 1);
        PROFILE("render imgui pass") {
        PROFILE_GPU("imgui pass") {
        simgui_render();
        }
        }
        sg_end_pass();
        PROFILE("render commit") {
        sg_commit();
        PROFILE_GPU_COLLECT();
        renderer_present_default_swapchain(r->window);
        }
        return;
    }

    sg_pass pass = {};
    pass.action.colors[0].load_action = SG_LOADACTION_CLEAR;
    pass.action.colors[0].store_action = SG_STOREACTION_STORE;
    pass.action.colors[0].clear_value = { 0.1f, 0.1f, 0.1f, 0.0f };
    pass.action.depth.load_action = SG_LOADACTION_CLEAR;
    pass.action.depth.store_action = SG_STOREACTION_DONTCARE;
    pass.action.depth.clear_value = 1.0f;
    pass.action.stencil.load_action = SG_LOADACTION_CLEAR;
    pass.action.stencil.store_action = SG_STOREACTION_DONTCARE;
    pass.action.stencil.clear_value = 0;
    // Backend-managed default surface (GL framebuffer 0 or current WebGPU canvas texture).
    if (!renderer_fill_default_swapchain(&pass.swapchain, win_w, win_h)) {
        fprintf(stderr, "Failed to acquire default swapchain\n");
        return;
    }

    sg_begin_pass(&pass);
    draw_world(r, scene, cam, overlay, nodes, splat_effect, SplatRenderMode::AlphaBlendSorted);
    PROFILE("render imgui pass") {
    PROFILE_GPU("imgui pass") {
    simgui_render(); // imgui draws on top of the world inside the same pass
    }
    }
    sg_end_pass();
    PROFILE("render commit") {
    sg_commit();
    PROFILE_GPU_COLLECT();
    renderer_present_default_swapchain(r->window);
    }
}

void renderer_destroy(Renderer* r) {
    renderer_destroy_shader_pipelines(r);
    if (r->overlay_sampler.id)    sg_destroy_sampler(r->overlay_sampler);
    if (r->mesh_sampler.id)       sg_destroy_sampler(r->mesh_sampler);
    if (r->accum_sampler.id)      sg_destroy_sampler(r->accum_sampler);
    if (r->gaussian_buffer_view.id) sg_destroy_view(r->gaussian_buffer_view);
    if (r->gaussian_buffer.id)    sg_destroy_buffer(r->gaussian_buffer);
    renderer_destroy_stochastic_targets(r);
    if (r->cube_vertex_buffer.id) sg_destroy_buffer(r->cube_vertex_buffer);
    if (r->cube_index_buffer.id)  sg_destroy_buffer(r->cube_index_buffer);
    if (r->index_buffer.id)       sg_destroy_buffer(r->index_buffer);
    if (r->unsorted_index_buffer.id) sg_destroy_buffer(r->unsorted_index_buffer);
    mesh_gpu_release(&r->mesh_gpu);
    mesh_gpu_release(&r->object_gpu);
}
